### DISCUSSION TITLE
would it be possible to add types as kind or part of kind?

### DISCUSSION THREAD

**Discussion by nanisyako** [srl-labs/containerlab#1195] [Ideas]
instead of binding each device's port-mapping separately would it be possible to define a generic type that the nodes can inherit from such as?

```
 kinds:
    ceos:
      image: ceos:4.28.0F
      type: 7500E
      binds:
        - 7500.json:/mnt/flash/EosIntfMapping.json:ro
      type: 7050SX3
      binds:
        - sx3.json:/mnt/flash/EosIntfMapping.json:ro
 ```
 then my nodes can be just :
 ```
   nodes:
    ### SPINES ###
    spine1:
      type: 7500E
      group: spine
      mgmt_ipv4: 172.80.80.21
    spine2:
      type: 7500E
      group: spine
      mgmt_ipv4: 172.80.80.22
    spine3:
      type: 7500E
      group: spine
      mgmt_ipv4: 172.80.80.23
 ```

**Comment by steiler** [comment]
It is also possible to define properties per Kind as well as a default, which will then apply to all of the nodes in den topology.
See https://containerlab.dev/manual/topo-def-file/#kinds and https://containerlab.dev/manual/topo-def-file/#defaults

**Comment by nanisyako** [comment]
thanks Steiler but in my case the kind will always be the same. I just want to mimic different arista platforms with the same image. It did not let me define ceos twice otherwise that would've worked as well.

**Comment by hellt** [comment]
Your example should work as you pasted it. If it doesn't work - please provide the error message

**Comment by nanisyako** [comment]
Hi @hellt here is the error:
```
12 topology:
 13   defaults:
 14     kind: ceos
 15
 16
 17   kinds:
 18     ceos:
 19       image: ceos:4.28.0F
 20       type: 7500E
 21       binds:
 22         - 7500.json:/mnt/flash/EosIntfMapping.json:ro
 23       type: 7050SX3
 24       binds:
 25         - sx3.json:/mnt/flash/EosIntfMapping.json:ro
 ```
```
INFO[0000] Containerlab v0.34.0 started
Error: failed to read topology file: yaml: unmarshal errors:
  line 23: field type already set in type types.NodeDefinition
  line 24: field binds already set in type types.NodeDefinition
  ```

and here is how I have hte nodes configured:

```

  nodes:
    ### SPINES ###
    spine1:
      type: 7500E
      group: spine
      mgmt_ipv4: 172.80.80.21
    spine2:
      type: 7500E
      group: spine
      mgmt_ipv4: 172.80.80.22
    spine3:
      type: 7500E
      group: spine
      mgmt_ipv4: 172.80.80.23

    ### LEAFS ###
    leaf1:
      type: 7050SX3
      mgmt_ipv4: 172.80.80.11
      group: leaf
    leaf2:
      type: 7050SX3
      group: leaf
      ```

**Reply by hellt** [reply]
ah, not enough coffee this morning.

Yes, you can't define the same keys in YAML, so the options you have:

1. you define your _default_ ceos kind with options that are common for the most of your topology nodes, and then on a node level you add specifics. For example
```yaml
name: ceos

topology:
  kinds:
    ceos:
      image: ceos:4.29
      type: 7220
      binds:
        - mapping.json:/mnt/flash/EosIntfMapping.json:ro

  nodes:
    ceos1:
      kind: ceos
      type: 7230
    ceos2:
      image: registry.dev/ceos:4.28.0F
```
In the topology above, the `ceos` kind defines the default type and binds mapping. The specific ceos nodes ceos1 and ceos2 override the needed parts as you need.

2. Another approach is to use [templated topologies](https://containerlab.dev/lab-examples/templated01/) where using Go templates you can defined multiple variables and use them in the topo as you see fit
