### DISCUSSION TITLE
multiple vlans inside a single topology?

### DISCUSSION THREAD

**Discussion by unikzforce** [srl-labs/containerlab#1359] [Q&A]
Hello team,

is it possible to define separate vlans inside a single Containerlab topology?

I mean something similar to this hypothetical and imprecise topology:

```
version: "1.0"

topology:
  nodes:
    source:
      image: ubuntu
      networks:
        - net1:
           ipv4_address: 192.168.1.2
    switch:
      image: ubuntu
      networks:
        - net1:
          ipv4_address: 192.168.1.3
        -  net2:
            ipv4_address: 192.168.2.2
    destination:
       image: ubuntu
       networks:
         - net1:
            ipv4_address: 192.168.2.3
networks:
  net1:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
  net2:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24
```
