### DISCUSSION TITLE
get license file from a remote URL

### DISCUSSION THREAD

**Discussion by jcpvdm** [srl-labs/containerlab#1376] [Ideas]
For example:

```
topology:
  kinds:
    vr-sros:
      image: registry.srlinux.dev/pub/vr-sros:23.3R2
      type: sr-1
      license: ftp://user:pass@1.2.3.4/licenses.txt
```
