### DISCUSSION TITLE
option to add additional disks to nodes

### DISCUSSION THREAD

**Discussion by jcpvdm** [srl-labs/containerlab#1405] [Ideas]
Hello, 
In some scenarios extra storage space is needed on the node.
For example in case of Nokia SR-OS, logging or persistence files for subscriber-management can take a lot of space depending on the config. Virtualized CPM supports the addition of extra Compact-Flashes (CF1, CF2) disks as .qcow2 images. So I thought this could be a nice feature to add in containerlab. 

I was thinking something like this that would allow to bind a custom .qcow2 image from the host to the node:
```
  nodes:
    r01:
      startup-config: r01.cfg
      kind: vr-sros
      type: >- 
        cp: cpu=2 ram=4 cf1=cf1.qcow2 chassis=SR-7 slot=A card=cpm5 ___
        lc: cpu=2 ram=4 max_nics=10 chassis=SR-7 slot=1 card=iom4-e-b mda/1=me10-10gb-sfp+
```

**Comment by hellt** [comment]
Hi @jcpvdm 
I wonder if the qcow2 needs to be on the host? Or can it rather be created in the container image on-the-fly before starting up a VM?

**Reply by jcpvdm** [reply]
Having it on the host would facilitate persistence of the image across destroy / deploy and give more control to the user to manipulate it. Creating it on-the-fly in the container, I don't see an easy way to provide this flexibility to user.

**Reply by hellt** [reply]
I see, then I think what can be done already to day is the following:

```yaml
r01:
  binds:
    - some.qcow2:/cf1.qcow2
  type: >- 
        <cp and lc config> ___
        cf: cf1=/cf1.qcow2 cf2=/cf2.qcow2
```

then in the vrnetlab we will have to parse the `cf1:` block and add the relevant qemu flags to mount such disk images to the VM

**Reply by jcpvdm** [reply]
I just noticed that having dual-cp is not yet supported right? It would be nice to add this feature too :) 
Assuming a dual-cp scenario, the cf option would need to be somehow coupled per cp to allow possibility of having different cf disks per cp.

About the manipulation of the cf .qcow2 images, maybe an hybrid approach can also be considered which is to create the cf images on-the-fly if not already exist, similar to what is done with the .cfg files. This would still allow some control to the user to replace the images and modifying the content from the host.

for example, creating cf1 with size=2G if file not exist yet on the binded directory:
```
  nodes:
    r01:
      startup-config: r01.cfg
      kind: vr-sros
      type: >- 
        cp: cpu=2 ram=4 cf1=2G chassis=SR-7 slot=A card=cpm5 ___
        lc: cpu=2 ram=4 max_nics=10 chassis=SR-7 slot=1 card=iom4-e-b mda/1=me10-10gb-sfp+
```
