### DISCUSSION TITLE
After the host machine rebooted, the links between nodes disappeared.

### DISCUSSION THREAD

**Discussion by binw666** [srl-labs/containerlab#1451] [Q&A] [answered]
Topology definition file as follow:
```yml
name: test
topology:
  nodes:
    node1:
      kind: linux
      image: ubuntu
    node2:
      kind: linux
      image: ubuntu
    node3:
      kind: linux
      image: ubuntu
  links:
    - endpoints: ["node1:ens1", "node2:ens1"]
    - endpoints: ["node1:ens2", "node3:ens1"]
```
After the host machine rebooted, the links between nodes disappeared.
```bash
root@node1:/# cat proc/net/dev 
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
    lo:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
  eth0:    3600      36    0    0    0     0          0         0      946      11    0    0    0     0       0          0
```
Is there any way to recover the links without damaging the containers? Or any way to keep the links even after the host machine has been rebooted？
