### DISCUSSION TITLE
Feature Request: declare static IP for macvlan endpoints

### DISCUSSION THREAD

**Discussion by pdumais** [srl-labs/containerlab#1702] [Ideas]
When using "network-mode: none" on a node, and then creating an explicit link for the management interface, it would be nice to have a way to specify a static IP since "mgmt-ipv4" has not effect anymore.

For example:
```
name: test1 
topology:
    linux:
      image: centos
  nodes:
    linux:
      kind: linux
      network-mode: none
  links:
      - type: macvlan
        endpoint:
            node: linux
            interface: eth0
            mac: 6C:62:86:00:00:02
        host-interface: eth1
        mode: bridge
```
in this case, since the container usually doesn't start a dhcp-client, it wouldn't receive an IP. 
So the container needs to be modified to either assign itself an IP from its entrypoint, or run dhclient. In each case, it means that the entrypoint of the container needs modification. 
It would be helpful if an IP, defined in the extended link definition, could be assigned to the interface immediately after its creation by containerlab, the same way docker would do it. This would allow us to retain the functionality of "mgmt-ipv4" while using a macvlan or other type of link.
