### DISCUSSION TITLE
SROS: map port from higher (>32) range to be used within containerlab

### DISCUSSION THREAD

**Discussion by sdktr** [srl-labs/containerlab#1880] [Q&A]
Hi; trying to run a lab where a specific (100G) upstream port from a high-port platform is used to connect. E.g.: leaf IXR-s has 48 10G ports and port >49 are 100G. I'm trying to map port 49 using containerlab.

But [this](https://github.com/srl-labs/containerlab/commit/58bea8b16e3ded8976e4776ebf9064d2d5d70403) naming check causes containerlab to fail the deployment. 

My question is: can I map a specific port within SROS (e.g. 49) to e.g. eth11, so it falls within the appearant max ethernet check of SROS/Containerlab? I have no need to use >5 interfaces of this node in the lab, but just need them to come from the higher port range.

Generated clab.yml by [netlab](https://github.com/ipspace/netlab)

```yaml
name: ml_8

mgmt:
  network: nl_mgmt_8
  ipv4-subnet: 192.168.8.0/24
  # Note: 'start' not validated
  bridge: nl_mgmt_8
topology:
  nodes:
    S1:
      mgmt-ipv4: 192.168.8.101
      kind: vr-sros
      type: 'ixr-x1'
      image: vrnetlab/vr-sros:23.10.R1
      runtime: docker
      license: ../../sros/license-sros23.3.R3-202310.txt
    L1:
      mgmt-ipv4: 192.168.8.102
      kind: vr-sros
      type: 'ixr-s'
      image: vrnetlab/vr-sros:23.10.R1
      runtime: docker
      license: ../../sros/license-sros23.3.R3-202310.txt


  links:
  - endpoints:
    - "S1:eth1"
    - "L1:eth33"
```
