### DISCUSSION TITLE
Disable NAT for MGMT network

### DISCUSSION THREAD

**Discussion by c-po** [srl-labs/containerlab#2268] [Q&A]
Hi,

I could not find anything in the documentation. When containerlab is started a new management network for docker is created with the management IP prefix.

Inspecting iptables I noticed that NAT is enabled for this prefix. As I wan't to use a routed mgmt network so I can access my lab nodes from external systems and also properly setup tacacs I would like to disable NAT.

Is there an easy way to disable MGMT network NAT in the topology definition?

Or is there a way to pass nerd know options to the docker driver like:

```yaml
networks:
  network-name:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.gateway_mode_ipv4: 'routed'
```
