### DISCUSSION TITLE
Group enhancement

### DISCUSSION THREAD

**Discussion by asadarafat** [srl-labs/containerlab#2343] [Ideas] [answered]
The current group implementation, as documented [[here](https://containerlab.dev/manual/nodes/#group)](https://containerlab.dev/manual/nodes/#group), only supports using strings for topology generation.

It would be beneficial to enhance this functionality by introducing a `level` metadata attribute for groups, defined globally. 

For example:

```yaml
topology:
  defaults:
    labels:
      groups:
        - name: "Data Center Spine"
          level: 1
        - name: "Data Center Leaf"
          level: 2
```

With this enhancement, the `level` metadata could be utilized to create layouts where parent nodes are arranged radially, hierarchically or what ever layout algorithm based on their level.

**Comment by FloSch62** [comment]
I think most of tools available via the graph command using the naming graph-level 
  labels:
    graph-level: 1 
    graph-icon: host 
    
Having labels available via a group could slim down some .clab.ymls

**Reply by hellt** [reply, marked as answer]
yep, the right way to do that is via `labels`, not `groups`. Groups were once misued for it, but it was a wrong choice

**Reply by asadarafat** [reply]
> yep, the right way to do that is via `labels`, not `groups`. Groups were once misued for it, but it was a wrong choice

So, the topology with labes should be like this? 

```
name: demo-ci

topology:  
  nodes:
    Spine-01:
      kind: srl
      image: ghcr.io/nokia/srlinux
      labels:
        topoViewer-role: spine
        topoViewer-group: "Data Center Spine"
        topoViewer-groupLevel: 1

    Spine-02:
      kind: srl
      image: ghcr.io/nokia/srlinux
      labels:
        topoViewer-role: spine
        topoViewer-group: "Data Center Spine"
        topoViewer-groupLevel: 1

    Leaf-01:
      kind: srl
      image: ghcr.io/nokia/srlinux
      labels:
        topoViewer-role: spine
        topoViewer-group: "Data Center Leaf"
        topoViewer-groupLevel: 2    

    Leaf-02:
      kind: srl
      image: ghcr.io/nokia/srlinux
      labels:
        topoViewer-role: spine
        topoViewer-group: "Data Center Leaf"
        topoViewer-groupLevel: 2
```

**Reply by FloSch62** [reply]
Yes this something you can already do today, but as said, just use the same labels as the other graph tools ( graph-level, graph-icon ) to keep it compatible. I think the topoViewer, does not need its own labels ;) 

For example https://github.com/netreplica/nrx is using the same labels as my clab-io-draw

**Reply by asadarafat** [reply]
Got it... 

side question..  to make the yaml definition shorter, any plan to support `yaml Anchors`?

```
name: demo-ci

globals:
  groups:
    spine: &spineGroup
      group: "Data Center Spine"
      graph-level: 1
    leaf: &leafGroup
      topoViewer-group: "Data Center Leaf"
      level: 2

topology:  
  nodes:
    Spine-01:
      kind: srl
      image: ghcr.io/nokia/srlinux
      labels:
        topoViewer-role: spine
        <<: *spineGroup

    Spine-02:
      kind: srl
      image: ghcr.io/nokia/srlinux
      labels:
        topoViewer-role: spine
        <<: *spineGroup

    Leaf-01:
      kind: srl
      image: ghcr.io/nokia/srlinux
      labels:
        topoViewer-role: spine
        <<: *leafGroup

    Leaf-02:
      kind: srl
      image: ghcr.io/nokia/srlinux
      labels:
        topoViewer-role: spine
        <<: *leafGroup
```
