### DISCUSSION TITLE
Facing error while deploying xrd routers using containerlab

### DISCUSSION THREAD

**Discussion by rahulsharma02jul** [srl-labs/containerlab#2370] [Q&A]
Hi Experts,
I am trying to deploy xrd routers using containerlab with this small .yaml file
```
name: sr

topology:
  nodes:

    xrd1:
      kind: cisco_xrd
      image: xrd-control-plane:24.4.1
      startup-config: xrd1.cfg
      cmd: /bin/bash

    xrd2:
      kind: cisco_xrd
      image: xrd-control-plane:24.4.1
      startup-config: xrd2.cfg
      cmd: /bin/bash

  links:
    - endpoints: ["xrd1:Gi0-0-0-0", "xrd2:Gi0-0-0-0"]
```
When i try to deploy using sudo clab deploy -c... it creates the containers but immediately powers them off and shows below error:
```
ERRO[0002] failed deploy stage for node "xrd1": Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown 
ERRO[0002] failed deploy stage for node "xrd2": Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown
```

If i remove the cmd statements, it shows below error:
```
ERRO[0000] failed deploy stage for node "xrd2": Error response from daemon: no command specified 
ERRO[0000] failed deploy stage for node "xrd1": Error response from daemon: no command specified
```

Please suggest, Thanks in advance
