### DISCUSSION TITLE
Ansible / SSH into router

### DISCUSSION THREAD

**Discussion by msaqib** [srl-labs/containerlab#486] [Q&A]
Hi
I have setup a lab using the FRR routers example. I am trying to run Ansible commands against the routers from the host running containerlab. One use case is to gather configuration, another use case is to configure the router. I believe Ansible uses SSH to connect to the routers. Is this doable either from the host running containerlab or from an Ansible container inside containerlab?
Thanks 
Saqib

**Comment by hellt** [comment]
Hi
yes, it is doable, the nodes are reachable from the host that runs containerlab
you can use IP addresses or domain names

moreover, the ansible inventory is generated once the lab finishes deploying - https://containerlab.srlinux.dev/manual/inventory/

**Reply by msaqib** [reply]
Hmm. I have set up the following playbook:

```
- name: testing facts
  hosts: routers
  tasks:
  - name: testing
    ansible.builtin.setup:
      gather_subset:
        - '!all'
        - '!any'
        - facter
  - name: Do not collect hardware facts
    frr.frr.frr_facts:
      gather_subset:
      - '!hardware'
```

When I run it, I get the following error. 

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AssertionError: socket_path must be a value
```
fatal: [172.20.20.7]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1625066800.395063-114528947878628/AnsiballZ_frr_facts.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1625066800.395063-114528947878628/AnsiballZ_frr_facts.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1625066800.395063-114528947878628/AnsiballZ_frr_facts.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.frr.frr.plugins.modules.frr_facts', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_frr.frr.frr_facts_payload_myc0q502/ansible_frr.frr.frr_facts_payload.zip/ansible_collections/frr/frr/plugins/modules/frr_facts.py\", line 425, in <module>\n  File \"/tmp/ansible_frr.frr.frr_facts_payload_myc0q502/ansible_frr.frr.frr_facts_payload.zip/ansible_collections/frr/frr/plugins/modules/frr_facts.py\", line 410, in main\n  File \"/tmp/ansible_frr.frr.frr_facts_payload_myc0q502/ansible_frr.frr.frr_facts_payload.zip/ansible_collections/frr/frr/plugins/modules/frr_facts.py\", line 134, in __init__\n  File \"/tmp/ansible_frr.frr.frr_facts_payload_myc0q502/ansible_frr.frr.frr_facts_payload.zip/ansible_collections/frr/frr/plugins/module_utils/network/frr/frr.py\", line 18, in get_capabilities\n  File \"/tmp/ansible_frr.frr.frr_facts_payload_myc0q502/ansible_frr.frr.frr_facts_payload.zip/ansible/module_utils/connection.py\", line 121, in __init__\nAssertionError: socket_path must be a value\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

Any idea what might be causing it?

**Reply by hellt** [reply]
no idea,
but likely there is something with the network connectivity to the node
check that you can access the frr nodes over the network using either the IP or the dns name, then check what you have in your inventory

**Reply by msaqib** [reply]
Yes, that inventory file is produced:

```
all:
  children:
    linux:
      hosts:
        clab-frrlab-PC1:
          ansible_host: 172.20.20.3
        clab-frrlab-PC2:
          ansible_host: 172.20.20.5
        clab-frrlab-PC3:
          ansible_host: 172.20.20.7
        clab-frrlab-router1:
          ansible_host: 172.20.20.2
        clab-frrlab-router2:
          ansible_host: 172.20.20.6
        clab-frrlab-router3:
          ansible_host: 172.20.20.4
```

The ping to the IP for which I am getting error is successful. Any suggestions for debugging?
