### ISSUE TITLE
ceos startup-config conflicts with ports

### ISSUE THREAD

**Issue by acesaa** [srl-labs/containerlab#1016]
9 times out of 10, when I deploy using both a startup-config and ports map, I am unable to ssh into the nodes from my workstation. I can ssh into the nodes from the server running containerlab. And also 'docker ps' indicates the ports were mapped as specified.

If I remove the "startup-config" line from my topology file the connection from my workstation to the mapped ports work every time. 

This is without making any changes to custom-ceos.cfg. Ultimately, I will modify this file to specify a default admin password and append a line "aaa authorization exec default local".

Steps to reproduce:
1. download https://github.com/srl-labs/containerlab/blob/master/nodes/ceos/ceos.cfg save as custom-ceos.cfg
2. create the following topology file:
```
name: test

topology:
  kinds:
    ceos: 
      startup-config: custom-ceos.cfg
  nodes:
    spine1:
      kind: ceos
      image: ceos
      ports:
        - 3001:22/tcp
    spine2:
      kind: ceos
      image: ceos
      ports:
        - 3002:22/tcp

  links:
    - endpoints: ["spine1:eth1", "spine2:eth1"]

``` 
3. sudo clab dep
4. attempt to ssh from a remote host to [server] port 3001 or port 3002 ** Connection times out **

host os: Ubuntu 22.04
clab version: 0.31.1
ceos version: 4.28.2F
