### ISSUE TITLE
Ignite Runtime Sequential Start

### ISSUE THREAD

**Issue by steiler** [srl-labs/containerlab#1039]
When introducing the DM, I've unfortunately removed some serialization methods for the creation of nodes, which kicked in whith the ignite runtime.

#1037 Re-introduces this serialization via the Dependency Manager.

Unfortunately this does not yet bring the ignite runtime fully back to life.

Considering the following topo:
```
name: cvx01

topology:
  nodes:
    sw1:
      kind: cvx
      image: networkop/cx:4.3.0
    sw2:
      kind: cvx
      image: networkop/cx:4.3.0

  links:
    - endpoints: ["sw1:swp11", "sw2:swp21"]
```

I've debugged stuff now to the point where I can say that from a clab perspective, on the second VM, the following call does not return
https://github.com/srl-labs/containerlab/blob/2818a4af443c6754d62b4f207b7d5407f41a18d4/runtime/ignite/ignite.go#L192

further down in the weaveworks ignite code we are stuck in the following loop.
https://github.com/weaveworks/ignite/blob/84f4c84ae5b3f1b924ad5ba7521328de1a1c0f89/pkg/metadata/metadata.go#L91-L102

Further investigation is required.
