### ISSUE TITLE
If an image doesn't have an explicit `latest` tag specified, it isn't pulled from a registry

### ISSUE THREAD

**Issue by bortok** [srl-labs/containerlab#1093]
If an image doesn't have an explicit `latest` tag specified, it isn't pulled from a registry.
Example for graphite image.

clab.topo.yml snippet
```Yaml
    graphite:
      kind: linux
      image: netreplica/graphite
      env:
        CLAB_SSH_CONNECTION: ${SSH_CONNECTION}
      binds:
        - __clabDir__/topology-data.json:/htdocs/default/default.json:ro
      ports:
        - 8080:80
      exec:
        - sh -c 'graphite_motd.sh 8080'
      labels:
        graph-hide: yes
```

When being deployed, clab doesn't try to pull it:

```
ERRO[0000] failed deploy phase for node "graphite": Error response from daemon: No such image: netreplica/graphite:latest
```

Pulls fine when changed `image: netreplica/graphite:latest`:

```
INFO[0000] Pulling docker.io/netreplica/graphite:latest Docker image
INFO[0007] Done pulling docker.io/netreplica/graphite:latest
```

`version: 0.32.4`
