### ISSUE TITLE
Podman Runtime - netns not created/found

### ISSUE THREAD

**Issue by DerInti** [srl-labs/containerlab#1130]
Hi, 
I cannot get any topology to spin up when utilizing the podman runtime. It seems the network namespaces are not getting created correctly.

- containerlab Version: 0.33.0
- Podman Version: 4.3.1, Network Backend: netavark
- Kernel: 6.0.12

The same issue is observed with earlier Kernel/Podman/Containerlab Versions.

### Topology
```
# a topo of debian routers
name: deblab

topology:
  kinds:
    linux:
      env:
        DEBIAN_FRONTEND: noninteractive
        VTYSH_PAGER: less -EFX
  nodes:
    R1:
      kind: linux
      image: debian:11-slim
    R2:
      kind: linux
      image: debian:11-slim
  links:
    - endpoints: ["R1:r1-2", "R2:r2-1"]
``` 

### Setting
Trying a simple topology of debian routers (which runs flawless in docker). 
The deployment seems to run fine until the links get created. The logs state network namespaces got created.

```plain
DEBU[0000] Created a container with ID e22b358e4fb81f99f6b31351b495849b7fa4e21fd3432e3f0154190292a7c79b, warnings [] and error <nil>
DEBU[0000] DoRequest Method: POST URI: http://d/v4.3.1/libpod/containers/e22b358e4fb81f99f6b31351b495849b7fa4e21fd3432e3f0154190292a7c79b/start
DEBU[0000] Created a container with ID 01733cef4503572a3de1d768a417ef36f174518678d69d3b8081586222b5197f, warnings [] and error <nil>
DEBU[0000] DoRequest Method: POST URI: http://d/v4.3.1/libpod/containers/01733cef4503572a3de1d768a417ef36f174518678d69d3b8081586222b5197f/start
DEBU[0000] DoRequest Method: GET URI: http://d/v4.3.1/libpod/containers/01733cef4503572a3de1d768a417ef36f174518678d69d3b8081586222b5197f/json
DEBU[0000] DoRequest Method: GET URI: http://d/v4.3.1/libpod/containers/e22b358e4fb81f99f6b31351b495849b7fa4e21fd3432e3f0154190292a7c79b/json
DEBU[0000] Method GetNSPath was called with a resulting nspath "/run/netns/netns-21bd508a-786b-ad05-5368-d3f49f134b1b"
DEBU[0000] Method GetNSPath was called with a resulting nspath "/run/netns/netns-90515364-a4d2-803b-147d-54b10e69024b"
```
But once reaching the creation of virtual wires:
``` 
DEBU[0000] Link worker 0 received link: link [R1:r1-2, R2:r2-1]
INFO[0000] Creating virtual wire: R1:r1-2 <--> R2:r2-1
ERRO[0000] failed to Statfs "/run/netns/netns-513abe72-8b76-8341-6bee-f17f10e41cb0": no such file or directory
DEBU[0001] Link worker 0 terminating...
```

Symlinks for the namespaces are created according to the specification - but they are dangling:
```
$ ip netns list
clab-deblab-R2
clab-deblab-R1
$ ls /run/netns -l
total 0
lrwxrwxrwx 1 root root 53 Dec 13 20:48 clab-deblab-R1 -> /run/netns/netns-513abe72-8b76-8341-6bee-f17f10e41cb0
lrwxrwxrwx 1 root root 53 Dec 13 20:48 clab-deblab-R2 -> /run/netns/netns-4a770d61-25bc-056f-d16d-56751930cee2
```

The debugging output is shortened - it contained no obvious line what failed. 
If more (or more verbose) output or configuration details are necessary I am happy to make them available. :)

**Comment by hellt** [comment]
pinging @LimeHat, checking if you have time to look at that...

@DerInti podman is in experimental stage still, so there is little attention to this runtime in general. You'll have to switch to docker runtime if you want a smooth ride. As for Podman, there is no reaction time we can give you, unless someone who has podman runtime and willing to check the code gets to it

**Comment by steiler** [comment]
The issue as I see it is, that you @DerInti did not supply any cmd or entrypoint.
There is no default for these in the debian images, because it is meant to be taken as a base image to be further refined.

Using a cmd with e.g. `sleep infinity` will keep the container alive. Which was the underlaying problem, symlinks exist, but the referenced namespace (or container) has vanished (transitioned into stopped state).

Can you confirm this @DerInti? 

Anyways, as @hellt mentioned, you should use docker runtime for the time being.

```
# a topo of debian routers
name: deblab

topology:
  nodes:
    R1:
      kind: linux
      image: debian:11-slim
      cmd: "sleep infinity"
    R2:
      kind: linux
      image: debian:11-slim
      cmd: "sleep infinity"
  links:
    - endpoints: ["R1:r1-2", "R2:r2-1"]
```
