### ISSUE TITLE
Post deploy commands

### ISSUE THREAD

**Issue by mtucker502** [srl-labs/containerlab#1182]
Is it possible to run commands within containers after deployment? I'd like to define these commands in the topology itself or specify a filename where the commands reside.

This is required to make crpd useful since even if a startup-config is provided commands still need to be run within the container.

**Comment by mtucker502** [comment]
I see that the deploy command has a flag to skip post deploy actions but the documentation contains no examples of actual post deploy actions.

The nearest example I can find is in the frr01 lab example ([https://github.com/srl-labs/containerlab/blob/main/lab-examples/frr01/run.sh](https://github.com/srl-labs/containerlab/blob/main/lab-examples/frr01/run.sh)) but this is using shell commands rather than the `clab deploy` interface directly.

**Comment by hellt** [comment]
Hi @mtucker502 
you should use `exec` stanza for executing commands in the container namespace https://containerlab.dev/manual/nodes/#exec

if you need to run a cli command on crpd, then I think crpd should have some CLI process that can take in commands to run as arguments.

Let me know if this helps

**Comment by mtucker502** [comment]
Thanks @hellt. This is exactly what I was looking for.

An example for anyone else looking for the same:

```yaml
name: crpddemo1

topology:
  nodes:
    crpd1:
      kind: crpd
      image: crpd:latest
      startup-config: crpd.conf
      exec:
        - ip addr add 100.64.1.1/30 dev eth1
        - ip addr add 1.1.1.1/32 dev lo
    crpd2:
      kind: crpd
      image: crpd:latest
      startup-config: crpd.conf
      exec:
        - ip addr add 100.64.1.2/30 dev eth1
        - ip addr add 2.2.2.2/32 dev lo

  links:
    - endpoints: ["crpd1:eth1", "crpd2:eth1"]
```

Contents of crpd.conf:

```
system {
    root-authentication {
        encrypted-password "$6$lB5c6$Zeud8c6IhCTE6hnZxXBl3ZMZTC2hOx9pxxYUWTHKW1oC32SATWLMH2EXarxWS5k685qMggUfFur1lq.o4p4cg1"; ## SECRET-DATA
    }
}
protocols {
    ospf {
        area 0.0.0.0 {
            interface eth1;
        }
    }
}
```

Validation

```
$ docker exec -it clab-crpddemo1-crpd1 cli
root@crpd1> show ospf neighbor
Address          Interface              State           ID               Pri  Dead
100.64.1.2       eth1                   Full            2.2.2.2          128    33

root@crpd1>
```
