### ISSUE TITLE
Not able to define a link with interfaces prefixed with swp

### ISSUE THREAD

**Issue by bjorntimmer** [srl-labs/containerlab#1222]
I'm trying to create a topology with a CVX node (from the lab example), however when I try to start the topology I got the message:
"Error: "sw1" interface name "swp12" doesn't match the required pattern. It should be named as ethX, where X is >0"

The topology file I'm using is:
```
name: cvx02

topology:
  nodes:
    sw1:
      kind: cvx
      image: networkop/cx:5.3.0
      runtime: docker
      binds:
        - /lib/modules:/lib/modules:ro # for kernel modules like ebtables
        - sw1/interfaces:/etc/network/interfaces
    h1:
      kind: linux
      image: networkop/host:ifreload
      binds:
        - h1/interfaces:/etc/network/interfaces
      cmd: 2 # wait for 2 interfaces to be connected: eth0 + eth1

  links:
    - endpoints: ["sw1:swp12", "h1:eth1"]
```
