### ISSUE TITLE
multilpe subnets inside a single topology?

### ISSUE THREAD

**Issue by unikzforce** [srl-labs/containerlab#1358]
Hello team,

is it possible to define separate network subnets inside a single Containerlab topology?

I mean something similar to this hypothetical topology:

```
version: "1.0"

topology:
  nodes:
    node1:
      image: nginx
      networks:
        net1:
          ipv4_address: 192.168.1.2/24
        net2:
          ipv4_address: 192.168.2.2/24
networks:
  net1:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
  net2:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24
```
