### ISSUE TITLE
Allow env variables in node image strings

### ISSUE THREAD

**Issue by jbemmel** [srl-labs/containerlab#1373]
Use case: Run CI/CD against a particular SR Linux release on a given type of emulated device

```
---
name: napalm-ci_cd

topology:
  kinds:
    srl:
      image: ghcr.io/nokia/srlinux:{ SRL_VERSION|"latest" }
      type: { SRL_TYPE | "ixrd2l" }
  nodes:
    srl:
      kind: srl
      mgmt_ipv4: 172.20.20.16
      mgmt_ipv6: 2001:172:20:20::16
```
