### ISSUE TITLE
Allow for point-to-point link interfaces to be named `eth0` when `network-mode=none`

### ISSUE THREAD

**Issue by marion-qacafe** [srl-labs/containerlab#1454]
When `network-mode` is set to `none` for a node, there is an error displayed when one of the point-to-point link interfaces is named `eth0`. If there is no interface attached to the management network, `eth0` should be allowed as a point-to-point link interface.

```
Error: eth0 interface can't be used in the endpoint definition as it is added by docker automatically: 'test-node:eth0'
```

**Comment by steiler** [comment]
Hi @marion-qacafe,
as a workaround try the following exec config:
```
name: linux

topology:
  kinds:
    linux:
      image: alpine
  nodes:
    l1:
      kind: linux
      network-mode: none
      exec:
        - ip l set dev eth1 down
        - ip l set dev eth1 name eth0
        - ip l set dev eth0 up
  
  links:
    - endpoints: ["l1:eth1","host:l1eth"]
```

**Comment by marion-qacafe** [comment]
Thanks for the workaround! Unfortunately, this won't work for my use case - I'm running OpenWRT, which expects the interfaces to be correctly named when it starts. It also doesn't include the `ip` command.

**Comment by hellt** [comment]
Hi @marion-qacafe 
yes, what you say makes perfect sense to me; when docker doesn't manage the networking stack (network-mode:none), it shouldn't complain about `eth0` link being set.
We will eventually fix this.

**Comment by hellt** [comment]
@marion-qacafe 

in the unreleased version we have added support for managing eth0 interfaces manually.
You can get the build by running
```
docker run --rm -v $(pwd):/workspace ghcr.io/oras-project/oras:v0.12.0 pull ghcr.io/srl-labs/clab-oci:4d3661c8
```

Then your topology would look like:

```yaml
name: wrt

topology:
  kinds:
    linux:
      image: alpine:3
  nodes:
    l1:
      kind: linux
      network-mode: none
    l2:
      kind: linux
  links:
    - endpoints: ["l1:eth0","l2:eth1"]
```
