### ISSUE TITLE
CSR1000v not able to communicate

### ISSUE THREAD

**Issue by sebaz9130** [srl-labs/containerlab#1459]
Hi guys, I have tested the tool and I got the containers up and running. Once configured they cannot ping each other.

Containerlab version 0.42.0
CSR images 16.12.05, 17.03.02

Topology as follows:
```
name: firstlab

topology:
  nodes:
    csr-r1:
      kind: vr-csr
      image: vrnetlab/vr-csr:17.03.02
    csr-r2:
      kind: vr-csr
      image: vrnetlab/vr-csr:17.03.02
      env:
        BOOT_DELAY: 30

  links:
    - endpoints: ["csr-r1:eth1", "csr-r2:eth1"] 
```
