### ISSUE TITLE
ARM support is a must for cLab in 2023

### ISSUE THREAD

**Issue by ankudinov** [srl-labs/containerlab#1472]
According to the [installation docs](https://containerlab.dev/install/#mac-os) ARM is currently not supported by Containerlab.  
The reasons are explained in #927  
Nevertheless it's not valid in 2023 any more. There is quite some work around this as more users are getting ARM based MAC laptops and this can hit at scale very soon.
I'd say an assumption that there will be only x86 in the field is incorrect now and every container build must be adjusted to multi-platform.

Normally it's as easy as:

```
# setup qemu
  - name: setup QEMU
    uses: docker/setup-qemu-action@v2
    with:
      platforms: "linux/arm64/v8,linux/amd64"
  # setup buildx
  - name: setup buildX
    uses: docker/setup-buildx-action@v2
```

I assume, that would be very similar for a bit more advanced clab build process.
Please do not close this issue as there is a number of Containerlab users that will be desperately waiting for ARM compatible release.
