### ISSUE TITLE
vMX communicating with interfaces eth1+

### ISSUE THREAD

**Issue by akielaries** [srl-labs/containerlab#1493]
I am trying to setup a lab with some vMX and vSRX nodes but I am noticing only the 0th interfaces ge-0/0/0 are able to ping eachother on all nodes. I see in the documentation for the vMX and SR Linux lab [example](https://containerlab.dev/lab-examples/vr-vmx/) only the 0th interfaces are connected and in the vMX documentation [here](https://containerlab.dev/manual/kinds/vr-vmx/) it says `Data interfaces eth1+ need to be configured with IP addressing manually using CLI/management protocols.` Even when doing so I get no result, hopefully I am not missing anything? I have Juniper's vJunosEvolved and vJunos-switch working in containerlab but same result as well, only communication through the first com interface et-0/0/0 (ge-0/0/0)

**Comment by hellt** [comment]
lets' see if someone has seen anything like it
https://discord.com/channels/860500297297821756/865572929601142845/1135856765242712135

**Comment by hellt** [comment]
I can't reproduce, and people in discord say they haven't seen anything like that either.

Here is the lab I used

```yaml
name: vmx
topology:
  nodes:
    vmx1:
      kind: vr-juniper_vmx
      image: vr-vmx:22.2R1.9
    l1:
      kind: linux
      image: alpine:3
      exec:
        - ip addr add 192.168.0.2/24 dev eth1
        - ip addr add 192.168.1.2/24 dev eth2

  links:
    - endpoints: [vmx1:eth1, l1:eth1]
    - endpoints: [vmx1:eth2, l1:eth2]
```

I configured the ge-0/0/0 and ge-0/0/1 and it all worked well.

```
admin@vmx1> show interfaces terse    
Interface               Admin Link Proto    Local                 Remote
ge-0/0/0                up    up
ge-0/0/0.0              up    up   inet     192.168.0.1/24  
                                   multiservice
lc-0/0/0                up    up
lc-0/0/0.32769          up    up   vpls    
pfe-0/0/0               up    up
pfe-0/0/0.16383         up    up   inet    
                                   inet6   
pfh-0/0/0               up    up
pfh-0/0/0.16383         up    up   inet    
pfh-0/0/0.16384         up    up   inet    
ge-0/0/1                up    up
ge-0/0/1.0              up    up   inet     192.168.1.1/24  
                                   multiservice
ge-0/0/2                up    down
ge-0/0/2.16386          up    down
```


I suppose your image was either not built correctly or you have changed the hellt/vrnetlab code somehow that messed with the datapath scripts?
