### ISSUE TITLE
Add `ansible_httpapi_use_proxy: false` to the generated ansible inventory

### ISSUE THREAD

**Issue by hellt** [srl-labs/containerlab#1569]
Since clab generated inventory assumes that the HTTP client that uses it resides on the same host, we have to add `ansible_httpapi_use_proxy: false` variable to the inventory to make sure we instruct the module to not attempt using global proxy if it is configured.

A comment should be added next to this var explaining this.

**Comment by steiler** [comment]
is this what you would expect? 
Like vars under all or should it be different?
```
all:
  vars:
    ansible_httpapi_use_proxy: false
  children:
    linux:
      hosts:
        clab-host-link-l1:
          ansible_host: 172.20.20.2
```
