### ISSUE TITLE
Default veth link mtu should be 9232 (for all links?)

### ISSUE THREAD

**Issue by hellt** [srl-labs/containerlab#1580]
In a lab like this

```yaml
name: sros
topology:
  nodes:
    sros:
      kind: vr-nokia_sros
      image: registry.srlinux.dev/pub/vr-sros:23.7.R1
      license: sros23.key
    srl:
      kind: nokia_srlinux
      image: ghcr.io/nokia/srlinux:23.7.1

  links:
    - endpoints: [sros:eth1, srl:e1-1]
```

the link MTU on srl and sros have different mtu value.

srl (e1-1) - 9232
sros (eth1) - 1500

This is wrong, we should use the jumbo mtu - 9232 (see note) - on all veth links installed in netns of a node.

TODO:

- [x] check what the mtu was pre links PR. It was likely less than 9232, because some nodes were not able to handle that MTU value. **Add**: the const DefaultVethLinkMTU is set to 9500 and this value we need to use

**Comment by steiler** [comment]
There is a 9500 mentioned in the code.
https://github.com/srl-labs/containerlab/blob/main/clab/config.go#L34-L35

**Comment by hellt** [comment]
@steiler yes, I think this is the value that used to work, because I remember originally we had like 65000 mtu and it didn't quite work for all =)

this const needs to be used in the veth link

**Comment by steiler** [comment]
Yes double checked with v0.41.0 and the MTU is 9500.

```
name: sros

topology:
  nodes:
    n1:
      kind: vr-sros
      image: vr-sros:23.3.R1
     ....
  links:
    - endpoints: ["n1:eth4", "host:n1e4"]
```
mava@server01:~/projects/containerlab3$ ip l show dev n1e4
52: n1e4@if53: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9500 qdisc noqueue state UP mode DEFAULT group default 
    link/ether aa:c1:ab:68:3a:e7 brd ff:ff:ff:ff:ff:ff link-netnsid 4
