### ISSUE TITLE
clab exec optimization

### ISSUE THREAD

**Issue by BurlyLuo** [srl-labs/containerlab#1615]
if define something at exec part:, there will be issue with below situation.
an other option that to full all the actions in one shell script.
```
cat <<EOF>clab.yaml | clab deploy -t clab.yaml -
name: ipsec
topology:
  nodes:
    gwx:
      kind: linux
      image: 192.168.2.100:5000/nettool
      exec:
      - ip a a 10.1.5.1/24 dev net1
      - ip a a 10.1.8.1/24 dev net2
      - ip a a 10.1.9.1/24 dev net3

    ipsec1:
      kind: linux
      image: 192.168.2.100:5000/nettool
      exec:
      - ip a a 10.244.1.1/24 dev eth1
      - ip addr add 10.1.5.10/24 dev eth2
      
      - ID=0xfe51d978
      - KEY=0xfa42aa6bc685beb4d967057134dd8e327ca179a6
      - ip xfrm state add src 10.1.5.10 dst 10.1.8.10 proto esp spi $ID reqid $ID mode tunnel aead 'rfc4106(gcm(aes))' $KEY 128
      - ip xfrm state add src 10.1.8.10 dst 10.1.5.10 proto esp spi $ID reqid $ID mode tunnel aead 'rfc4106(gcm(aes))' $KEY 128
      
      - ip xfrm policy add src 10.244.1.10/24 dst 10.244.2.10/24 dir out tmpl src 10.1.5.10 dst 10.1.8.10 proto esp reqid $ID mode tunnel
      - ip xfrm policy add src 10.244.2.10/24 dst 10.244.1.10/24 dir fwd tmpl src 10.1.8.10 dst 10.1.5.10 proto esp reqid $ID mode tunnel
      - ip xfrm policy add src 10.244.2.10/24 dst 10.244.1.10/24 dir in  tmpl src 10.1.8.10 dst 10.1.5.10 proto esp reqid $ID mode tunnel

```

```
INFO[0003] Adding containerlab host entries to /etc/hosts file 
ERRO[0006] failed to create exec in container /clab-ipsec-ipsec2: Error response from daemon: No exec command specified 
ERRO[0006] clab-ipsec-ipsec2: failed to execute cmd: "" with error Error response from daemon: No exec command specified 
INFO[0006] Executed command "ip a a 10.244.1.1/24 dev eth1" on the node "ipsec1". stdout: 
INFO[0006] Executed command "ip addr add 10.1.5.10/24 dev eth2" on the node "ipsec1". stdout: 
ERRO[0006] Failed to execute command "ID=0xfe51d978" on the node "ipsec1". rc=126,
stdout:
OCI runtime exec failed: exec failed: unable to start container process: exec: "ID=0xfe51d978": executable file not found in $PATH: unknown

stderr: 
ERRO[0006] Failed to execute command "KEY=0xfa42aa6bc685beb4d967057134dd8e327ca179a6" on the node "ipsec1". rc=126,
stdout:
OCI runtime exec failed: exec failed: unable to start container process: exec: "KEY=0xfa42aa6bc685beb4d967057134dd8e327ca179a6": executable file not found in $PATH: unknown

stderr: 
ERRO[0006] Failed to execute command "ip xfrm state add src 10.1.5.10 dst 10.1.8.10 proto esp spi reqid mode tunnel aead rfc4106(gcm(aes)) 128" on the node "ipsec1". rc=255,
stdout:
```
