### ISSUE TITLE
macvlan links are broken

### ISSUE THREAD

**Issue by hellt** [srl-labs/containerlab#1633]
We broke macvlan links recently.
Lanching this lab fails with an error "Invalid Argument"

```yaml
name: srl
topology:
  nodes:
    srl:
      kind: nokia_srlinux
      image: ghcr.io/nokia/srlinux:23.7.1
  links:
    - endpoints: ["srl:e1-1", "macvlan:ens3"]
```

we need to add a test for macvlan link. The test case should use `ip route` to detect outgoing interface to smth like 1.1.1.1 and then using this interface in the link section to create macvlan
