### ISSUE TITLE
Documentation for extended link format is erroneous

### ISSUE THREAD

**Issue by pdumais** [srl-labs/containerlab#1643]
In https://containerlab.dev/manual/topo-def-file/#macvlan, it is shown:
```
 links:
  - type: macvlan
    endpoint:
      - node: <NodeA-Name>                  # mandatory
        interface: <NodeA-Interface-Name>   # mandatory
        mac: <NodeA-Interface-Mac>          # optional
    host-interface: <interface-name>        # mandatory
    mode: <macvlan-mode>                    # optional ("bridge" by default)
    vars: <link-variables>                  # optional (used in templating)
    labels: <link-labels>                   # optional (used in templating)
```

But The node under the endpoint is not a list. Defining it as a list makes clab throw an error: `cannot unmarshal !!seq into links.EndpointRaw`

It does work if defining as:
```
 links:
  - type: macvlan
    endpoint:
        node: <NodeA-Name>                  # mandatory
        interface: <NodeA-Interface-Name>   # mandatory
        mac: <NodeA-Interface-Mac>          # optional
    host-interface: <interface-name>        # mandatory
    mode: <macvlan-mode>                    # optional ("bridge" by default)
    vars: <link-variables>                  # optional (used in templating)
    labels: <link-labels>                   # optional (used in templating)
```
