### ISSUE TITLE
netplanner interface script and link provisioning issues

### ISSUE THREAD

**Issue by hellt** [srl-labs/containerlab#1733]
The following topology fails during the link creation, supposedly due to netplanner interfering with regular links provisioning:

```yaml
name: denog

topology:
  nodes:
    srv2:
      binds:
        - netplanner.yaml:/etc/netplanner/netplanner.yaml
      kind: linux
      user: root
      image: ghcr.io/cellebyte/denog-evpn-to-the-host/netplanner-frr-fabric:0.0.1
  links:
    - endpoints: ["srv2:lf1", "host:bla1"]
```

netplanner.yaml:

```yaml
network:
  version: 3
  ethernets:
    lf1:
      mtu: 9100
      link-local: [ipv6]
      vrf: Vrf_underlay
      emit-lldp: true
      accept-ra: false
  renderer: networkd
```
