### ISSUE TITLE
Version 0.44 breaks bridging on Rocky 9.3

### ISSUE THREAD

**Issue by bartv** [srl-labs/containerlab#1739]
We have a number of containerlabs that put a port in the mgmt network. Like this:

```
  - endpoints: [switch-1:eth10, mgmt-net:sw1-xe-9]
```

We use it with a juniper qfx but we see the same problems with the new vjunosswitch.

It works fine with version 0.43 and it started failing with 0.44. At that point we downgraded, we now tested again with 0.48 and it still does not work.

When running tcpdump on the host and monitor on the switch we see no traffic going through.

All other functionality seems to work fine.

**Comment by steiler** [comment]
Hi @bartv,
thanks for reaching out. Quickly tried this slim sample topology:
````
name: mgmtnetif

topology:
  nodes:
    l1:
      kind: linux
      image: alpine:latest
      cmd: sleep infinity
  links:
    - endpoints: [l1:eth1, mgmt-net:l1eth1]
```
And I can confirm that the link is created, but on the host side it is missing the reference to the _master_, meaning the bridge it should attach to.
Let me fix this.
