### ISSUE TITLE
Kind references not resolving properly

### ISSUE THREAD

**Issue by steiler** [srl-labs/containerlab#1771]
We have kind aliases, such that srl == nokia_srlinux etc.

It should be possible to define the following topology:

```
topology:
  kinds:
    srl:
      type: ixrd3
  nodes:
    n1:
      kind: nokia_srlinux
      image: ghcr.io/nokia/srlinux:23.10.1
```
Notice the kinds definition referes `srl` whilst the node itself referes to `nokia_srlinux`.
This will not apply the `type` attribute to the `n1` node. I think some form of resolution should take place and these config parts should be merged.
