### ISSUE TITLE
macvlan and vr-based nodes

### ISSUE THREAD

**Issue by hellt** [srl-labs/containerlab#1814]
It has been reported that vr-based nodes have datapath connectivity issue when using the macvlan mode.

Considering the following topology:

```yaml
name: mvlantest


topology:
  kinds:
    vr-sros:
      image: vrnetlab/vr-sros:22.5.R1
      license: license-vsr-i-22.txt
 
  nodes:
    pe1:
      kind: vr-sros

  links:
    - endpoints: ["pe1:eth1", "macvlan:ens33"]
```

the following has been observed:

The ping replies initiated from vr node to an IP reachable from the macvlan segment do not propagate to the macvlan interface from the parent interface:

![image](https://github.com/srl-labs/containerlab/assets/5679861/c173a8bf-173c-4f34-9401-528a6c1fa338)

I think this might be related to the `tc mirred` redirect rules, which might require some tuning for macvlan interfaces?

**Comment by hellt** [comment]
setting the macvlan mode to passthru solved this
need to check if our default bridge mode must be switched to passthru

**Comment by steiler** [comment]
Passthru: allows a single VM to be connected directly to the physical interface.

I don't think this is what we want?!
I exposed the `mode` in the extensive version of the MacVlan link definition. So simply set it that way.
https://containerlab.dev/manual/topo-def-file/#macvlan

**Comment by hellt** [comment]
the question is why in bridge mode connectivity breaks, and what passthru does differently

**Comment by marcosfsch** [comment]
I was testing this scenario and confirm that connectiviy work only with passthru mode, but LLDP doesn't. I fixed the issue setting the corresponding ethX contaner interface to promiscuous mode.
I believe the reason why bridge mode doesn't work is because the interface insede QEMU is using a different mac address than tha macvlan interface. Probably if it uses the same one it should work transparently.

**Comment by hellt** [comment]
the promisc mode is now being enabled by default on macvlan interfaces

https://github.com/srl-labs/containerlab/pull/2460

**Comment by brenton-h** [comment]
Is this still present in v0.68? Or was it supposed to be resolved with #2460 ?

I see the same issue trying to use macvlan on SROS dataplane interfaces e.g  eth1 or 1/1/1 - ARP (and ICMP) are not getting through.

`  links:
    - endpoints: ["ixre1:eth1", "macvlan:ens3f0"]
`

I have tcpdumped it - For SROS initiated ping attempt I can see both inbound/outbound ARP Req/Reply on the containerlab host ens3f0. But on SROS container interface eth1 I can only see the SROS-initiated ARP, not the reply.

I also tried:

```
  links:
  - type: macvlan
    endpoint:
      node: ixre1
      interface: eth1
    host-interface: ens3f0
    mode: passthru
```

but with passthru option it gives the error and the interface never comes up in SROS:
16:54:00 INFO Creating MACVLAN link: host:ens3f0 <--> ixre1:eth1
16:54:00 ERRO failed deploy links for node "ixre1": invalid argument

**Comment by evilmonkey19** [comment]
Probably #2865 is related

**Comment by tvarohohlavy** [comment]
I can confirm, that issue is with the different MAC between macvlan interface and container interface as setting them to the same is ok:

Link:
```
    - type: macvlan
      endpoint:
        node: "vios01"
        interface: "eth3"
        mac: 0c00.aaaa.aaaa
      host-interface: ens192
      mode: bridge
```

Container interface on Cisco IOSv:
```
vios01#show run int gi0/3     
Building configuration...

Current configuration : 123 bytes
!
interface GigabitEthernet0/3
 mac-address 0c00.aaaa.aaaa
 ip address dhcp
 duplex auto
 speed auto
 media-type rj45
end

vios01#show ip int brief Gi0/3
Interface                  IP-Address      OK? Method Status                Protocol
GigabitEthernet0/3         10.124.0.203    YES DHCP   up                    up      

vios01#ping 10.124.0.1
Type escape sequence to abort.
Sending 5, 100-byte ICMP Echos to 10.124.0.1, timeout is 2 seconds:
!!!!!
Success rate is 100 percent (5/5), round-trip min/avg/max = 4/5/8 ms
```

In my case VMware vDS Port group where the CLAB host is has disabled security to allow multiple MACs on the VM NIC.

Cisco Router upstream:
```
core-router01#show ip arp
Protocol  Address          Age (min)  Hardware Addr   Type   Interface
Internet  10.124.0.1              -   6c41.0ef8.067c  ARPA   Vlan6         # Subnet GW on this router
Internet  10.124.0.10             3   0050.5685.2eaf  ARPA   Vlan6       # CLAB Host (VM on VMware)
Internet  10.124.0.203            0   0c00.aaaa.aaaa  ARPA   Vlan6      # IOSv Container in CLAB, Gi0/3 respectively

core-router01#ping 10.124.0.203
Type escape sequence to abort.
Sending 5, 100-byte ICMP Echos to 10.124.0.203, timeout is 2 seconds:
!!!!!
Success rate is 100 percent (5/5), round-trip min/avg/max = 4/4/6 ms
core-router01#
```
