### ISSUE TITLE
having 2 Isolated Networks with similar subnets side by side

### ISSUE THREAD

**Issue by unikzforce** [srl-labs/containerlab#1816]
Hello containerlab team,

I have written an ebpf based software switch, I want to test it under containerlab,

I have previously tested my software using vmware + its LAN SEGMENT concept,
and it is working fine.

the vmware topology i'm using is this:

![image](https://github.com/srl-labs/containerlab/assets/7010566/bbeea63f-233a-424a-a537-5cbde7ccb0c9)

i have 3 vms:
- source --> 1 NIC --> `2.2.2.100/24`
- switch --> 2 NICs --> no ip for any of the NICs
- destination -> 1 NIC --> `2.2.2.200/24`

subnet of source:eth1 is equal to destination:eth1 --> both 2.2.2.x/24

and also i have created a 2 Lan Segments in vmware:
- one LAN SEGMENT for `source:eth1` and `switch:eth1`
- another LAN SEGMENT for `switch:eth2` and `destination:eth1`

be default you cannot ping 2.2.2.200 from source,
and you cannot ping 2.2.2.100 from destination.

whenever i start my software switch in `switch` vm, then `source` and `destination` can ping each other.
whenever i stop my software switch in `switch` vm, then `source` and `destination` cannot ping each other.

**is it possible to replicate the same topology with the same characteristics in containerlab?**

**Comment by hellt** [comment]
Hi @unikzforce 
yes, this is one of the basic topologies
In clab this translates to:

```yaml
name: ebpf

topology:
  nodes:
    src:
      kind: linux
      image: alpine:3
    sw:
      kind: linux
      image: mycustomebpfswitch:latest
    dst:
      kind: linux
      image: alpine:3
  links:
    - endpoints: [src:eth1, sw:eth1]
    - endpoints: [dst:eth1, sw:eth2]
```

This assumes your switch is packages as a container image under the name `mycustomebpfswitch:latest`
