### ISSUE TITLE
Document env vars access in exec commands

### ISSUE THREAD

**Issue by hellt** [srl-labs/containerlab#1938]
Variables require double `$$` to get access to the env vars:

```yaml
      env:
        FOO: BAR
      exec:
        - ash -c 'echo $$FOO'
```
