### ISSUE TITLE
`containerlab deploy` panics when sharing namespace with an existing container created by kind

### ISSUE THREAD

**Issue by terassyi** [srl-labs/containerlab#1939]
Hi, I found this problem after upgrading containerlab from 0.51.3 to 0.52.0.

## What

When I try to create a network with `kind`, `containerlab` panics with the following outputs.

```console
kind create cluster --name test  
Creating cluster "test" ...
 ✓ Ensuring node image (kindest/node:v1.26.3) 🖼 
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
Set kubectl context to "kind-test"
You can now use your cluster with:

kubectl cluster-info --context kind-test

Not sure what to do next? 😅  Check out https://kind.sigs.k8s.io/docs/user/quick-start/
sudo bin/containerlab deploy -t test.yaml deploy
INFO[0000] Containerlab v0.0.0 started                  
INFO[0000] Parsing & checking topology file: test.yaml  
INFO[0000] Creating lab directory: /home/terassyi/workspace/containerlab/clab-test 
WARN[0000] node test-control-plane refrenced in namespace sharing not found, considering it an external dependency. 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1a4aaca]

goroutine 1 [running]:
github.com/srl-labs/containerlab/clab/dependency_manager.(*DependencyNode).AddDepender(0x0, {0x29e66ef, 0x6}, 0xc0005a4b10, {0x29e66ef, 0x6})
        /home/terassyi/workspace/containerlab/clab/dependency_manager/dependency_node.go:133 +0x8a
github.com/srl-labs/containerlab/clab.(*CLab).createNamespaceSharingDependency(0xc0005a7550)
        /home/terassyi/workspace/containerlab/clab/clab.go:445 +0x1a6
github.com/srl-labs/containerlab/clab.(*CLab).CreateNodes(0xc0005a7550, {0x3131250, 0xc00089c320}, 0x2, 0x0)
        /home/terassyi/workspace/containerlab/clab/clab.go:387 +0x112
github.com/srl-labs/containerlab/cmd.deployFn(0x4783240?, {0x29e421a?, 0x4?, 0x29e421e?})
        /home/terassyi/workspace/containerlab/cmd/deploy.go:219 +0x10cf
github.com/spf13/cobra.(*Command).execute(0x4783240, {0xc0007a8120, 0x3, 0x3})
        /home/terassyi/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0x4780ce0)
        /home/terassyi/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /home/terassyi/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/srl-labs/containerlab/cmd.Execute()
        /home/terassyi/workspace/containerlab/cmd/root.go:49 +0x1a
main.main()
        /home/terassyi/workspace/containerlab/main.go:10 +0xf
```

My configuration is here.
```yaml
name: test
topology:
  kinds:
    linux:
      cmd: bash
  nodes:
    node0:
      kind: linux
      image: frrouting/frr:v8.4.0
      exec:
        - ip a
    control-plane:
      kind: linux
      image: nicolaka/netshoot:latest
      network-mode: container:test-control-plane
      exec:
        - ip a
  links:
    - endpoints: ["node0:net0", "control-plane:net0"]
```

## Why

I think this change(https://github.com/srl-labs/containerlab/pull/1902) is related to this problem.

This panic is caused by a nil pointer dereference in the following line.
https://github.com/srl-labs/containerlab/blob/622a2c831b4870be6bbc60de6d191217d78f7bda/clab/dependency_manager/dependency_node.go#L133

When running it with my configuration, I also found that `referencedNode` is nil at line 440.

https://github.com/srl-labs/containerlab/blob/de03337aa9742c5949d69eda2011099a39af5192/clab/clab.go#L440-L445

---

https://github.com/srl-labs/containerlab/pull/1902 seems to change the configuration format.
So, I'm not sure if this is a bug or a specification change.

**Comment by steiler** [comment]
Hi @terassyi,
thanks for reporting this issue. I messed up the dependency book keeping. As you see here, there was a `continue` if the referenceNode was not found, plus the warning that we expect the referenced node to be an external node. However re-orged and missed the continue. 
https://github.com/srl-labs/containerlab/commit/fff2a5408aa1eee88162a0f2c4b43faef454463d#diff-831ecb8143ceda28e72434a64e3b7f88d15f9492071603608fd0180ae3105e67L440-L444

I've submitted PR #1940 which should solve the issue.

**Comment by steiler** [comment]
@terassyi BTW: are you aware that you can make containerlab also deploy your kind cluster?!
Check out this:
https://containerlab.dev/manual/kinds/k8s-kind/

**Comment by terassyi** [comment]
I don't know that there is a such convenient feature!
Thank you for sharing!

I'll try to use this.

**Comment by steiler** [comment]
I can only advice you to keep a close eye on the release notes ;-)
https://containerlab.dev/rn/0.52/

**Comment by BurlyLuo** [comment]
```INFO[0000] Creating lab directory: /root/wcni-kind/LabasCode/flannel/4-flannel-vxlan-directrouting/clab-flannel-vxlan-directrouting 
WARN[0000] node flannel-vxlan-directrouting-worker2 referenced in namespace sharing not found in topology definition, considering it an external dependency. 
WARN[0000] node flannel-vxlan-directrouting-worker3 referenced in namespace sharing not found in topology definition, considering it an external dependency. 
WARN[0000] node flannel-vxlan-directrouting-control-plane referenced in namespace sharing not found in topology definition, considering it an external dependency. 
WARN[0000] node flannel-vxlan-directrouting-worker referenced in namespace sharing not found in topology definition, considering it an external dependency. 
```
combine with kind(k8s in docker). but got above WARN. 
```
[root@rowan> 4-flannel-vxlan-directrouting]# cat 2-setup-clab.sh 
#!/bin/bash
set -v

{ ip l s br-pool0 down;ip l d br-pool0; } > /dev/null 2>&1
{ ip l s br-pool1 down;ip l d br-pool1; } > /dev/null 2>&1
ip l a br-pool0 type bridge && ip l s br-pool0 up
ip l a br-pool1 type bridge && ip l s br-pool1 up

cat <<EOF>clab.yaml | clab deploy -t clab.yaml -
name: flannel-vxlan-directrouting
topology:
  nodes:
    gw0:
      kind: linux
      image: 192.168.2.100:5000/vyos/vyos:1.4.9
      cmd: /sbin/init
      binds:
        - /lib/modules:/lib/modules
        - ./startup-conf/gw0-boot.cfg:/opt/vyatta/etc/config/config.boot

    br-pool0:
      kind: bridge
  
    br-pool1:
      kind: bridge

    server1:
      kind: linux
      image: 192.168.2.100:5000/nettool
      network-mode: container:flannel-vxlan-directrouting-control-plane
      exec:
      - ip addr add 10.1.5.10/24 dev net0
      - ip route replace default via 10.1.5.1

    server2:
      kind: linux
      image: 192.168.2.100:5000/nettool
      network-mode: container:flannel-vxlan-directrouting-worker
      exec:
      - ip addr add 10.1.5.11/24 dev net0
      - ip route replace default via 10.1.5.1

    server3:
      kind: linux
      image: 192.168.2.100:5000/nettool
      network-mode: container:flannel-vxlan-directrouting-worker2
      exec:
      - ip addr add 10.1.8.10/24 dev net0
      - ip route replace default via 10.1.8.1

    server4:
      kind: linux
      image: 192.168.2.100:5000/nettool
      network-mode: container:flannel-vxlan-directrouting-worker3
      exec:
      - ip addr add 10.1.8.11/24 dev net0
      - ip route replace default via 10.1.8.1

  links:
    - endpoints: ["br-pool0:br-pool0-net0", "server1:net0"]
    - endpoints: ["br-pool0:br-pool0-net1", "server2:net0"]
    - endpoints: ["br-pool1:br-pool1-net0", "server3:net0"]
    - endpoints: ["br-pool1:br-pool1-net1", "server4:net0"]

    - endpoints: ["gw0:eth1", "br-pool0:br-pool0-net2"]
    - endpoints: ["gw0:eth2", "br-pool1:br-pool1-net2"]

EOF
[root@rowan> 4-flannel-vxlan-directrouting]# 
```
