### ISSUE TITLE
links vars broken since 0.43?

### ISSUE THREAD

**Issue by Bzhash** [srl-labs/containerlab#1942]
Seems to me that the usage of links vars in templates in clab _changed_ between 0.42 and 0.44. Testing with this command:
containerlab config -t test.yml  template --vars 

In 0.42 I get the expected 

```
clab_links:
- clab_far:
    clab_link_name: to_srl2
    clab_node: srl1
    port: ethernet-1/1
  clab_link_name: to_srl1
  port: ethernet-1/1
```

In 0.43 it fails

Error: failed to read topology file: yaml: unmarshal errors:
  line 171: field vars not found in type struct { Type string "yaml:\"type\""; Endpoints interface {} "yaml:\"endpoints\"" }

In 0.44 and later I just get

`clab_links: []`

# Ref test.yml:
```
name: srl
topology:
  nodes:
    srl1:
      kind: srl
      image: ghcr.io/nokia/srlinux
    srl2:
      kind: srl
      image: ghcr.io/nokia/srlinux
  links:
    - endpoints: ["srl1:e1-1", "srl2:e1-1"]
      vars:
        port: [ethernet-1/1, ethernet-1/1]
```
