### ISSUE TITLE
clab inspect -t <path> issues with v 0.53.0

### ISSUE THREAD

**Issue by tiago-amado** [srl-labs/containerlab#1982]
## clab inspect -t <path> issues with v 0.53.0
clab inspect -t <path> is working fine up to 0.52.0.
starting with 0.53.0 it is showing all existing containers in the server, including those that are not part of clab.

### Ok with 0.52.0
```yaml
[root@Airframe3 ~]# clab version
  ____ ___  _   _ _____  _    ___ _   _ _____ ____  _       _     
 / ___/ _ \| \ | |_   _|/ \  |_ _| \ | | ____|  _ \| | __ _| |__  
| |  | | | |  \| | | | / _ \  | ||  \| |  _| | |_) | |/ _` | '_ \ 
| |__| |_| | |\  | | |/ ___ \ | || |\  | |___|  _ <| | (_| | |_) |
 \____\___/|_| \_| |_/_/   \_\___|_| \_|_____|_| \_\_|\__,_|_.__/ 

    version: 0.52.0
     commit: de03337a
       date: 2024-03-05T11:44:25Z
     source: https://github.com/srl-labs/containerlab
 rel. notes: https://containerlab.dev/rn/0.52/
[root@Airframe3 ~]# 
[root@Airframe3 ~]# 
[root@Airframe3 ~]# clab inspect -t /home/meo/scripts_3B/meo_fase3B.yml
INFO[0000] Parsing & checking topology file: meo_fase3B.yml 
+---+----------+--------------+----------------------------+------------+---------+----------------+--------------+
| # |   Name   | Container ID |           Image            |    Kind    |  State  |  IPv4 Address  | IPv6 Address |
+---+----------+--------------+----------------------------+------------+---------+----------------+--------------+
| 1 | cr-bho2  | 7bfbe6e49d0c | vrnetlab/vr-sros:20.10.R10 | nokia_sros | running | 172.80.80.3/24 | N/A          |
| 2 | cr-ptm2  | 881ee512d086 | vrnetlab/vr-sros:20.10.R10 | nokia_sros | running | 172.80.80.2/24 | N/A          |
| 3 | sr-albf1 | 3604aaf63fd4 | vrnetlab/vr-sros:20.10.R10 | nokia_sros | running | 172.80.80.5/24 | N/A          |
| 4 | sr-pcs1  | 11ee4f8b73e4 | vrnetlab/vr-sros:19.10.R14 | nokia_sros | running | 172.80.80.4/24 | N/A          |
| 5 | sr-ptm1  | 7d3f4e87bb9d | vrnetlab/vr-sros:20.10.R10 | nokia_sros | running | 172.80.80.6/24 | N/A          |
| 6 | sr-ptm2  | b713d8668ed9 | vrnetlab/vr-sros:20.10.R10 | nokia_sros | running | 172.80.80.7/24 | N/A          |
| 7 | sr-ptm3  | 5eacd00d6717 | vrnetlab/vr-sros:16.0.R20  | nokia_sros | running | 172.80.80.8/24 | N/A          |
+---+----------+--------------+----------------------------+------------+---------+----------------+--------------+
[root@Airframe3 ~]# 
```

### NOK with 0.53.0
```yaml
[root@Airframe3 ~]# bash -c "$(curl -sL https://get.containerlab.dev)" -- -v 0.53.0
A newer containerlab 0.53.0 is available. Release notes: https://containerlab.dev/rn/0.53/
You are running containerlab 0.52.0 version
Proceed with upgrade? [Y/n]: Y
Downloading https://github.com/srl-labs/containerlab/releases/download/v0.53.0/containerlab_0.53.0_linux_amd64.rpm
Preparing to install containerlab 0.53.0 from package
  ____ ___  _   _ _____  _    ___ _   _ _____ ____  _       _     
 / ___/ _ \| \ | |_   _|/ \  |_ _| \ | | ____|  _ \| | __ _| |__  
| |  | | | |  \| | | | / _ \  | ||  \| |  _| | |_) | |/ _` | '_ \ 
| |__| |_| | |\  | | |/ ___ \ | || |\  | |___|  _ <| | (_| | |_) |
 \____\___/|_| \_| |_/_/   \_\___|_| \_|_____|_| \_\_|\__,_|_.__/ 

    version: 0.53.0
     commit: 7ce0afa2
       date: 2024-03-25T16:31:05Z
     source: https://github.com/srl-labs/containerlab
 rel. notes: https://containerlab.dev/rn/0.53/
[root@Airframe3 ~]# 
[root@Airframe3 ~]# 
[root@Airframe3 ~]# clab inspect -t /home/meo/scripts_3B/meo_fase3B.yml
INFO[0000] Parsing & checking topology file: meo_fase3B.yml 
+----+--------------------------+--------------+-------------------------------------------------+--------------+---------+-----------------+----------------------+
| #  |           Name           | Container ID |                      Image                      |     Kind     |  State  |  IPv4 Address   |     IPv6 Address     |
+----+--------------------------+--------------+-------------------------------------------------+--------------+---------+-----------------+----------------------+
|  1 | awesome_galois           | c9fcad936214 | ghcr.io/srl-labs/clab-io-draw:latest            |              | exited  | N/A             | N/A                  |
|  2 | edgeshark                | aaf5c7e3ca65 | ghcr.io/siemens/packetflix                      |              | created | 172.18.0.5/16   | N/A                  |
|  3 | edgeshark-edgeshark-1    | b1d4a0bf8a87 | ghcr.io/siemens/packetflix                      |              | running | 172.18.0.3/16   | N/A                  |
|  4 | edgeshark-gostwire-1     | 11d9973961bc | ghcr.io/siemens/ghostwire                       |              | running | 172.18.0.2/16   | N/A                  |
|  5 | gostwire                 | d615d1acac89 | ghcr.io/siemens/ghostwire                       |              | running | 172.18.0.4/16   | N/A                  |
|  6 | modest_jackson           | 87dbfd8963c6 | hello-world                                     |              | exited  | N/A             | N/A                  |
|  7 | ce5                      | b20bb8b81545 | registry.srlinux.dev/pub/vr-sros:23.10.R1       | nokia_sros   | running | 172.50.50.51/24 | N/A                  |
|  8 | ce6                      | 4eb670858fdf | registry.srlinux.dev/pub/vr-sros:23.10.R1       | nokia_sros   | running | 172.50.50.52/24 | N/A                  |
|  9 | client7                  | f2a7081860b3 | ghcr.io/srl-labs/network-multitool              | linux        | running | 172.50.50.31/24 | N/A                  |
| 10 | client8                  | d0e984da1e14 | ghcr.io/srl-labs/network-multitool              | linux        | running | 172.50.50.32/24 | N/A                  |
| 11 | gnmic                    | a1659e5201eb | ghcr.io/openconfig/gnmic:0.29.0                 | linux        | running | 172.50.50.21/24 | N/A                  |
| 12 | grafana                  | 9717fd00a399 | grafana/grafana:9.5.2                           | linux        | running | 172.50.50.23/24 | N/A                  |
| 13 | p3                       | e78dad907880 | registry.srlinux.dev/pub/vr-sros:23.10.R1       | nokia_sros   | running | 172.50.50.13/24 | N/A                  |
| 14 | p4                       | 7dbc14962280 | registry.srlinux.dev/pub/vr-sros:23.10.R1       | nokia_sros   | running | 172.50.50.14/24 | N/A                  |
| 15 | pe1                      | e0db90708b89 | registry.srlinux.dev/pub/vr-sros:23.10.R1       | nokia_sros   | running | 172.50.50.11/24 | N/A                  |
| 16 | pe2                      | eb47315af457 | registry.srlinux.dev/pub/vr-sros:23.10.R1       | nokia_sros   | running | 172.50.50.12/24 | N/A                  |
| 17 | prometheus               | 9e2c18cbf2fc | prom/prometheus:v2.35.0                         | linux        | running | 172.50.50.22/24 | N/A                  |
| 18 | clab-cisco_c8000v-c8000v | c1e63a34198f | registry.srlinux.dev/pub/cisco_c8000v:17.11.01a | cisco_c8000v | running | 172.20.20.4/24  | 2001:172:20:20::4/64 |
| 19 | IXR110                   | ed784e184f92 | ghcr.io/nokia/srlinux:23.7.2                    | srl          | running | 172.20.20.6/24  | 2001:172:20:20::6/64 |
| 20 | IXR111                   | 5fc84679e5ef | ghcr.io/nokia/srlinux:23.7.2                    | srl          | running | 172.20.20.8/24  | 2001:172:20:20::8/64 |
| 21 | IXR120                   | 956db7c0d64d | ghcr.io/nokia/srlinux:23.7.2                    | srl          | running | 172.20.20.7/24  | 2001:172:20:20::7/64 |
| 22 | IXR121                   | e0dd7dc0ea57 | ghcr.io/nokia/srlinux:23.7.2                    | srl          | running | 172.20.20.3/24  | 2001:172:20:20::3/64 |
| 23 | IXR220                   | fd6f0ad666a6 | ghcr.io/nokia/srlinux:23.7.2                    | srl          | running | 172.20.20.2/24  | 2001:172:20:20::2/64 |
| 24 | IXR221                   | 883357370fbb | ghcr.io/nokia/srlinux:23.7.2                    | srl          | running | 172.20.20.5/24  | 2001:172:20:20::5/64 |
| 25 | sr100                    | c74a01a12b03 | registry.srlinux.dev/pub/vr-sros:23.3.R1        | vr-sros      | running | 172.20.20.14/24 | 2001:172:20:20::e/64 |
| 26 | sr200                    | 3c62d9855861 | registry.srlinux.dev/pub/vr-sros:23.3.R1        | vr-sros      | running | 172.20.20.15/24 | 2001:172:20:20::f/64 |
| 27 | srv130                   | b35a81a68fcb | registry.srlinux.dev/pub/vr-sros:23.10.R3       | vr-sros      | running | 172.20.20.11/24 | 2001:172:20:20::b/64 |
| 28 | srv140                   | 3b9cc7da32c6 | registry.srlinux.dev/pub/vr-sros:23.10.R3       | vr-sros      | running | 172.20.20.13/24 | 2001:172:20:20::d/64 |
| 29 | srv141                   | ddbddd9f0561 | registry.srlinux.dev/pub/vr-sros:23.10.R3       | vr-sros      | running | 172.20.20.12/24 | 2001:172:20:20::c/64 |
| 30 | srv230                   | f05612ba1bd7 | registry.srlinux.dev/pub/vr-sros:23.10.R3       | vr-sros      | running | 172.20.20.9/24  | 2001:172:20:20::9/64 |
| 31 | ssh                      | 09cc52fa502d | netreplica/graphite:webssh2                     | linux        | running | 172.20.20.10/24 | 2001:172:20:20::a/64 |
| 32 | r101                     | b08fc07ab0c8 | registry.srlinux.dev/pub/vr-sros:23.10.R1       | vr-sros      | exited  | N/A             | N/A                  |
| 33 | r102                     | 5ac092ee9020 | registry.srlinux.dev/pub/vr-sros:23.10.R1       | vr-sros      | exited  | N/A             | N/A                  |
| 34 | r103                     | c99948c822ca | registry.srlinux.dev/pub/vr-sros:23.10.R1       | vr-sros      | exited  | N/A             | N/A                  |
| 35 | r104                     | 80fbd8230dd2 | registry.srlinux.dev/pub/vr-sros:23.10.R1       | vr-sros      | exited  | N/A             | N/A                  |
| 36 | cr-bho2                  | 7bfbe6e49d0c | vrnetlab/vr-sros:20.10.R10                      | nokia_sros   | running | 172.80.80.3/24  | N/A                  |
| 37 | cr-ptm2                  | 881ee512d086 | vrnetlab/vr-sros:20.10.R10                      | nokia_sros   | running | 172.80.80.2/24  | N/A                  |
| 38 | sr-albf1                 | 3604aaf63fd4 | vrnetlab/vr-sros:20.10.R10                      | nokia_sros   | running | 172.80.80.5/24  | N/A                  |
| 39 | sr-pcs1                  | 11ee4f8b73e4 | vrnetlab/vr-sros:19.10.R14                      | nokia_sros   | running | 172.80.80.4/24  | N/A                  |
| 40 | sr-ptm1                  | 7d3f4e87bb9d | vrnetlab/vr-sros:20.10.R10                      | nokia_sros   | running | 172.80.80.6/24  | N/A                  |
| 41 | sr-ptm2                  | b713d8668ed9 | vrnetlab/vr-sros:20.10.R10                      | nokia_sros   | running | 172.80.80.7/24  | N/A                  |
| 42 | sr-ptm3                  | 5eacd00d6717 | vrnetlab/vr-sros:16.0.R20                       | nokia_sros   | running | 172.80.80.8/24  | N/A                  |
| 43 | clab-sxr-sxr1d32d        | 07069e8569a3 | ghcr.io/nokia/srlinux                           | srl          | exited  | N/A             | N/A                  |
| 44 | clab-sxr-sxr1x44s        | 3499534fd50e | ghcr.io/nokia/srlinux                           | srl          | exited  | N/A             | N/A                  |
+----+--------------------------+--------------+-------------------------------------------------+--------------+---------+-----------------+----------------------+
[root@Airframe3 ~]# 
```

### Docker info
```yaml
[root@Airframe3 ~]# docker info
Client: Docker Engine - Community
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 44
  Running: 35
  Paused: 0
  Stopped: 9
 Images: 58
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc version: v1.1.10-0-g18a0cb0
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.14.0-362.8.1.el9_3.x86_64
 Operating System: Rocky Linux 9.3 (Blue Onyx)
 OSType: linux
 Architecture: x86_64
 CPUs: 64
 Total Memory: 376GiB
 Name: Airframe3
 ID: f126142a-28ea-4b07-bfbe-90d36f002124
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

[root@Airframe3 ~]# 
```
