### ISSUE TITLE
Ceos 4.30.5M version Interfaces and Links Problem

### ISSUE THREAD

**Issue by mahmutaydin1** [srl-labs/containerlab#2016]
Hi,

When I use below yaml to deploy topology, container lab gives below error about links. 
When I remove links from my yaml file, it is working. but this time, arista has no any interfaces except management.
Do you know why this is happening?
thank you

`root@ubuntu:~# containerlab  deploy -t docker-compose.yml
INFO[0000] Containerlab v0.54.2 started                 
Error: failed to read topology file: yaml: unmarshal errors:
  line 17: field links not found in type clab.Config
Consult with release notes to see if any fields were changed/removed`

```
`name: ceoslab
prefix: LAB
topology:

  kinds:
    ceos:


  nodes:
    ceos1:
      kind: ceos
      image: ceosimage:4.30.5M
    ceos2:
      kind: ceos
      image: ceosimage:4.30.5M

links:
  - endpoints: ["ceos1:eth1","ceos2:eth2"]`
```
