### ISSUE TITLE
startup-config problem

### ISSUE THREAD

**Issue by mahmutaydin1** [srl-labs/containerlab#2031]
Hello,

I am adding  starup-config under kinds. But when I deploy, config is not    written to devices. Could you please help for this problem?

**initialconf.cfg**
```

`interface management 0
no lldp transmit
no lldp receive
~        
```        

**topology file**

name: oderid
prefix: customer
mgmt:
  ipv4-subnet: 172.23.0.0/26

topology:

  kinds:
    ceos:
      image: ceosimage:4.30.5M
      startup-config: initialconf.cfg
      env:
        CLAB_MGMT_VRF: MGMT
  nodes:
    spine1:
      kind: ceos
    spine2:
      kind: ceos

    leaf1:
      kind: ceos

    leaf2:
      kind: ceos

    leaf3:
      kind: ceos

    leaf4:
      kind: ceos

    host1:
      kind: ceos

    host2:
      kind: ceos

  links:
    - endpoints: ["spine1:eth2", "leaf1:eth2"]
    - endpoints: ["spine1:eth3", "leaf2:eth2"]
    - endpoints: ["spine1:eth4", "leaf3:eth2"]
    - endpoints: ["spine1:eth5", "leaf4:eth2"]
    - endpoints: ["spine2:eth2", "leaf1:eth3"]
    - endpoints: ["spine2:eth3", "leaf2:eth3"]
    - endpoints: ["spine2:eth4", "leaf3:eth3"]
    - endpoints: ["spine2:eth5", "leaf4:eth3"]
    - endpoints: ["leaf1:eth1", "leaf2:eth1"]
    - endpoints: ["leaf1:eth6", "leaf2:eth6"]
    - endpoints: ["leaf3:eth1", "leaf4:eth1"]
    - endpoints: ["leaf3:eth6", "leaf4:eth6"]
    - endpoints: ["leaf1:eth4", "host1:eth1"]
    - endpoints: ["leaf2:eth4", "host1:eth2"]
    - endpoints: ["leaf3:eth4", "host2:eth1"]
    - endpoints: ["leaf4:eth4", "host2:eth2"]

**Comment by james-m-henderson** [comment]
I suspect the issue here is that you are changing parameters on the management IP, and that is being overridden by containerlab.

Here is a working example using Ethernet 1, for the lldp settings:

```
name: oderid
prefix: customer
mgmt:
  ipv4-subnet: 172.23.0.0/26

topology:
  kinds:
    ceos:
      #image: ceosimage:4.30.5M
      image: ceos:4.32.0F
      startup-config: initialconf.cfg
      env:
        CLAB_MGMT_VRF: MGMT

  nodes:
    spine1:
      kind: ceos

    spine2:
     kind: ceos

    leaf1:
      kind: ceos

    leaf2:
      kind: ceos

    leaf3:
      kind: ceos

    leaf4:
      kind: ceos

    host1:
      kind: ceos

    host2:
      kind: ceos

  links:
    - endpoints: ["spine1:eth2", "leaf1:eth2"]
    - endpoints: ["spine1:eth3", "leaf2:eth2"]
    - endpoints: ["spine1:eth4", "leaf3:eth2"]
    - endpoints: ["spine1:eth5", "leaf4:eth2"]
    - endpoints: ["spine2:eth2", "leaf1:eth3"]
    - endpoints: ["spine2:eth3", "leaf2:eth3"]
    - endpoints: ["spine2:eth4", "leaf3:eth3"]
    - endpoints: ["spine2:eth5", "leaf4:eth3"]
    - endpoints: ["leaf1:eth1", "leaf2:eth1"]
    - endpoints: ["leaf1:eth6", "leaf2:eth6"]
    - endpoints: ["leaf3:eth1", "leaf4:eth1"]
    - endpoints: ["leaf3:eth6", "leaf4:eth6"]
    - endpoints: ["leaf1:eth4", "host1:eth1"]
    - endpoints: ["leaf2:eth4", "host1:eth2"]
    - endpoints: ["leaf3:eth4", "host2:eth1"]
    - endpoints: ["leaf4:eth4", "host2:eth2"]
```

initialconf.cfg:
```
interface ethernet 1
 no lldp transmit
 no lldp receive
```

It is considerably easier to reproduce examples if the code is provided inside backtick fences as described in the [GitHub Basic writing and formatting syntax guide](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code).

**Comment by hellt** [comment]
as @james-m-henderson pointed out, the mgmt0 interface is part of the default config and when you need to add things to it you should use the original startup config we use: https://github.com/srl-labs/containerlab/blob/main/nodes/ceos/ceos.cfg

you can copy it entirely and add the bits you want under the `interface {{ .MgmtIntf }}` part.
This would add the necessary config for the mgmt0 while keeping the rest of the config provisioned in a way that allows you to get access to the node.

**Comment by mahmutaydin1** [comment]
@hellt  thank you for youe help. however, when I add as below, it still did not work. As you see, Iadded only no lldp statements under interface management 0.

however when containerlab is deploy, this statements are not see unde mgmt0

```
interface {{ .MgmtIntf }}
{{ if .Env.CLAB_MGMT_VRF }} vrf {{ .Env.CLAB_MGMT_VRF }}{{end}}
{{ if .MgmtIPv4Address }}ip address {{ .MgmtIPv4Address }}/{{.MgmtIPv4PrefixLength}}{{end}}
{{ if .MgmtIPv6Address }}ipv6 address {{ .MgmtIPv6Address }}/{{.MgmtIPv6PrefixLength}}{{end}}
no lldp transmit
no lldp receive
```

**Comment by hellt** [comment]
ah, yes, it is because ceos gets the Ma0 config over dhcp and rewrites the startup

what you need is this:

```yaml
name: ceos
topology:
  nodes:
    ceos1:
      kind: arista_ceos
      image: ceos:4.32.0F
      exec:
        - |-
          Cli -p 15 -c 'enable
          configure terminal
          interface Ma0
          no lldp transmit
          no lldp receive'
```
