### ISSUE TITLE
Issue with Arista version in quickstart topology

### ISSUE THREAD

**Issue by james-m-henderson** [srl-labs/containerlab#2033]
I went through the [quickstart](https://containerlab.dev/quickstart) guide and have noted a couple of issues.

The most significant is that the suggested version of Arista (4.25.0F) is not present on the Arista website for download. The closest I could find was 4.25.11M.

After downloading this version and running, containerlab seemed to hang indefinitely after doing `containerlab deploy`.

I noticed that while the docker VMs were up, if I try to use the Cli command on Arista, it doesn't work:

```
jmh@the-pot:~/clab-quickstart$ docker exec -it clab-srlceos01-ceos bash
bash-4.2# exit
jmh@the-pot:~/clab-quickstart$ docker exec -it clab-srlceos01-ceos Cli
OCI runtime exec failed: exec failed: unable to start container process: exec: "Cli": executable file not found in $PATH: unknown
```

In order to fix, I tried downloading the latest available Arista image, 4.32.0F. This works without flaw, topology starts up and the above Cli command works.

There was one other small flaw I noticed. The command given to connect to the srl container is wrong.

It is listed as:

```
docker exec -it clab-srlceos01-srl1 bash
```

It should be:

```
docker exec -it clab-srlceos01-srl bash
```

**Comment by james-m-henderson** [comment]
Here is the topology file with the "good" version activated and the "bad" version commented out:

```
# topology documentation: http://containerlab.dev/lab-examples/srl-ceos/
name: srlceos01

topology:
  nodes:
    srl:
      kind: nokia_srlinux
      image: ghcr.io/nokia/srlinux
    ceos:
      kind: arista_ceos
      image: ceos:4.32.0F
      #image: ceos:4.25.11M

  links:
    - endpoints: ["srl:e1-1", "ceos:eth1"]
```
