### ISSUE TITLE
mgmt network not working with macvlan

### ISSUE THREAD

**Issue by benbgg** [srl-labs/containerlab#2069]
Hi 
I have this macvlan network defined:
[
    {
        "Name": "newnet",
        "Id": "bd967f83ad36ebfc5a6d28bc507975c43e921cff25c004caf31f445f355e56d2",
        "Created": "2024-06-08T10:44:32.170746307+01:00",
        "Scope": "local",
        "Driver": "macvlan",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "192.168.37.0/24",
                    "Gateway": "192.168.37.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {},
        "Options": {
            "parent": "enp6s18"
        },
        "Labels": {}
    }
]
And this is my lab definition:
name: crpdlab01
mgmt:
  network: newnet
topology:
  nodes:
    crpd01:
      kind: juniper_crpd
      image: crpd-custom:latest
    crpd02:
      kind: juniper_crpd
      image: crpd-custom:latest
    crpd03:
      kind: juniper_crpd
      image: crpd-custom:latest
  links:
    - endpoints: ["crpd01:eth2", "crpd02:eth1"]
    - endpoints: ["crpd02:eth2", "crpd03:eth1"]
    - endpoints: ["crpd03:eth2", "crpd01:eth1"]
 but "sudo -E deploy" gives:
INFO[0000] Containerlab v0.54.2 started
INFO[0000] Parsing & checking topology file: crpdlan01.clab.yml
WARN[0000] failed gleaning v4 and/or v6 addresses from bridge via netlink, falling back to docker network inspect data
Error: failed to lookup link "br-bd967f83ad36": Link not found
Any suggestions?

Thanks in advance

**Comment by hellt** [comment]
Hi

My first suggestion would be to format your code with triple backticks to make sure you formatting is properly rendered.

But in general, macvlan mgmt networks are not currently supported.

**Comment by benbgg** [comment]
Oh dear - guess I'll have to work around it.
#1651 gave me the impression it was - kind of. 
Apologies for the formatting:
Thanks for the prompt answer
```
mgmt:
  network: newnet
topology:
  nodes:
    crpd01:
      kind: juniper_crpd
      image: crpd-custom:latest
    crpd02:
      kind: juniper_crpd
      image: crpd-custom:latest
    crpd03:
      kind: juniper_crpd
      image: crpd-custom:latest
  links:
    - endpoints: ["crpd01:eth2", "crpd02:eth1"]
    - endpoints: ["crpd02:eth2", "crpd03:eth1"]
    - endpoints: ["crpd03:eth2", "crpd01:eth1"]
```
