### ISSUE TITLE
Allow for a custom default admin password to be set via topology attributes 

### ISSUE THREAD

**Issue by hellt** [srl-labs/containerlab#2146]
Some lab environments restrict the users to have nodes with the default credentials shipped with the node (admin:admin, etc).

We must have a way to set the default password via the topology setting to mitigate this. Maybe an env var set for a node/kind/default that would set the credentials during the node registration.

**Comment by stkonst** [comment]
I see this issue is still open. Any plans to be fixed?

**Comment by hellt** [comment]
@stkonst what NOS do you need this for? Maybe it is already supported.

**Comment by stkonst** [comment]
Hi Roman,

I tried with SR-Linux and SR-OS but doesn't work: 
`topology:
  kinds:
     nokia_srlinux:
       user: stavros
  `

So I had to comment it out.

**Comment by hellt** [comment]
yes, we are not creating new local users based on `user: foo` parameter. If your goal is to have a node boot up with a new user added in addition to the default users provided by the NOS you will have to add a startup config that has this user defined.

For example, for SR Linux the following topology would create a single node with user `stavros` added:

```yaml
name: srl
topology:
  groups:
    srl-new-user:
      startup-config: |
        set / system aaa authentication user stavros password test superuser true
  nodes:
    srl1:
      kind: nokia_srlinux
      image: ghcr.io/nokia/srlinux:25.10
      group: srl-new-user
    srl2:
      kind: nokia_srlinux
      image: ghcr.io/nokia/srlinux:25.7
      group: srl-new-user
  links:
    - endpoints: [srl1:e1-1, srl2:e1-1]
```


after deploying this lab:

```
ssh -o IdentitiesOnly=yes stavros@clab-srl-srl1
Warning: Permanently added 'clab-srl-srl1' (ED25519) to the list of known hosts.
................................................................
:                  Welcome to Nokia SR Linux!                  :
:              Open Network OS for the NetOps era.             :
:                                                              :
:    This is a freely distributed official container image.    :
:                      Use it - Share it                       :
:                                                              :
: Get started: https://learn.srlinux.dev                       :
: Container:   https://go.srlinux.dev/container-image          :
: Docs:        https://doc.srlinux.dev/25-10                   :
: Rel. notes:  https://doc.srlinux.dev/rn25-10-1               :
: YANG:        https://yang.srlinux.dev/v25.10.1               :
: Discord:     https://go.srlinux.dev/discord                  :
: Contact:     https://go.srlinux.dev/contact-sales            :
................................................................

(stavros@clab-srl-srl1) Password:
Loading environment configuration file(s): ['/etc/opt/srlinux/srlinux.rc']
Welcome to the Nokia SR Linux CLI.

--{ running }--[  ]--
A:stavros@srl1#
```
