### ISSUE TITLE
Nodes' binds option mounts folders with uid of user instead of the root

### ISSUE THREAD

**Issue by mdahshan** [srl-labs/containerlab#2196]
Hi Team,

I am having an issue with the bind option for the node kind.

For the following topology:

```
    ftpserver:
      kind: linux
      image: ftpserver:latest
      group: server        
      binds:
        - ./vsftpd.conf:/etc/vsftpd/vsftpd.conf
  ```

When deploying the topology, the file vsftpd.conf has owner:group as 1000:1000 instead of the root.  This breaks the functionality of the vsftpd as it refuses to start due to incorrect owner.

This problem only happens on the amd64 version. The arm64 version mounts correctly with root ownership.

Containerlab version:

    version: 0.57.2
     commit: a6b1f044
       date: 2024-09-16T14:12:31Z

The Dockerfile for ftpservers looks as follows:

```
FROM alpine:latest
RUN apk add --no-cache vsftpd

EXPOSE 20 21

RUN rm -rf /var/cache/apk/*

ENTRYPOINT ["vsftpd", "/etc/vsftpd/vsftpd.conf"]

```

Thanks for your help
