### ISSUE TITLE
Graph feature on Containerlab not showing interface tags correctly

### ISSUE THREAD

**Issue by netwninja** [srl-labs/containerlab#2224]
**Issue:-** Graph feature on Containerlab displaying incorrect interface IDs. 

containerlab version:- 

```
sudo clab version
  ____ ___  _   _ _____  _    ___ _   _ _____ ____  _       _     
 / ___/ _ \| \ | |_   _|/ \  |_ _| \ | | ____|  _ \| | __ _| |__  
| |  | | | |  \| | | | / _ \  | ||  \| |  _| | |_) | |/ _` | '_ \ 
| |__| |_| | |\  | | |/ ___ \ | || |\  | |___|  _ <| | (_| | |_) |
 \____\___/|_| \_| |_/_/   \_\___|_| \_|_____|_| \_\_|\__,_|_.__/ 

    version: 0.57.5
     commit: fbca124e
       date: 2024-09-30T10:53:07Z
     source: https://github.com/srl-labs/containerlab
 rel. notes: https://containerlab.dev/rn/0.57/#0575

```
**Topology YAML** 

```
name: eos_mlag

topology:
  nodes:
    ceos1:
      kind: ceos
      image: ceos:4.32.0F
      startup-config: ceos1.cfg 
    ceos2:
      kind: ceos
      image: ceos:4.32.0F
      startup-config: ceos2.cfg
  links:
    - endpoints: ["ceos1:eth47", "ceos2:eth47"]
    - endpoints: ["ceos1:eth48", "ceos2:eth48"]

```

**LLDP output from COES1 & CEOS2**

```
ceos1#show lldp nei 
Last table change time   : 0:19:11 ago
Number of table inserts  : 3
Number of table deletes  : 0
Number of table drops    : 0
Number of table age-outs : 0

Port          Neighbor Device ID       Neighbor Port ID    TTL
---------- ------------------------ ---------------------- ---
Et47          ceos2                    Ethernet47          120
Et48          ceos2                    Ethernet48          120
Ma0           ceos2                    Management0         120

ceos2#show lldp nei 
Last table change time   : 0:19:21 ago
Number of table inserts  : 3
Number of table deletes  : 0
Number of table drops    : 0
Number of table age-outs : 0

Port          Neighbor Device ID       Neighbor Port ID    TTL
---------- ------------------------ ---------------------- ---
Et47          ceos1                    Ethernet47          120
Et48          ceos1                    Ethernet48          120
Ma0           ceos1                    Management0         120

```

**Graph Topology** 

![Screenshot from 2024-10-07 17-36-35](https://github.com/user-attachments/assets/a6198b93-8a51-4418-bddf-2e847be24533)
