### ISSUE TITLE
Timeout error on postdeploy task when using partial startup-config on SROS node

### ISSUE THREAD

**Issue by guicale** [srl-labs/containerlab#2234]
I've been trying to deploy a lab using a simple topology with a partial startup config, but this always results in the error `failed to run postdeploy task for node R1: failed to apply config; error: errTimeoutError: channel timeout sending input to device`. The startup config fails to be applied, but the lab works otherwhise. From the error message, it seems to be related to scrapligo, which emits the error [here](https://github.com/scrapli/scrapligo/blob/9baa9c5dc83eda2fc8c32042ce0799478009f95d/driver/netconf/rpc.go#L101).

This is running containerlab 0.57.5 with docker 27.2.0.

The topology and config files are as follows.
**nrs1_03.yml**
```
name: nrs1_03

topology:
  kinds:
    nokia_sros:
      type: >-
        cp: cpu=2 ram=4 chassis=SR-7 sfm=m-sfm5-7 slot=A card=cpm5 ___
        lc: cpu=2 ram=4 max_nics=4 chassis=SR-7 sfm=m-sfm5-7 slot=1 card=iom4-e mda/1=me10-10gb-sfp+
      image: vrnetlab/vr-sros:24.7.R1
      license: /opt/sros_licenses.txt
  nodes:
    R1:
      kind: nokia_sros
      startup-config: R1.partial.txt
```
**R1.partial.txt**
```
configure {
	card 1 {
		card-type iom4-e
		mda 1 {
			mda-type me10-10gb-sfp+
		}
	}
	port 1/1/1 {
		admin-state enable
	}
	port 1/1/2 {
		admin-state enable
	}
	port 1/1/3 {
		admin-state enable
	}
	port 1/1/4 {
		admin-state enable
	}
}
```
Edit: the partial config seems to work if written in full-context form, like this:
```
/configure card 1 card-type iom4-e
/configure card 1 mda 1 mda-type me10-10gb-sfp+
/configure port 1/1/1 admin-state enable
/configure port 1/1/2 admin-state enable
/configure port 1/1/3 admin-state enable
/configure port 1/1/4 admin-state enable
```
Edit 2:
Changing the first partial config to use spaces instead of tabs gives a different error: `failed to run postdeploy task for node R1: failed to apply config; error: <nil> operation error from multiple inputs. 8 indicated errors`.
