### ISSUE TITLE
Containerlab generate command not rendering link properly for juniper kind

### ISSUE THREAD

**Issue by devangnp** [srl-labs/containerlab#2328]
containerlab generate command not generating the links properly incase of juniper_* kinds. It renders proper connections with cEOS kind. 

```
root@ubuntu:~/clab# containerlab generate --name 2tier --kind juniper_vjunosswitch --nodes 2,2
name: 2tier
prefix: null
mgmt: {}
settings: null
topology:
  nodes:
    node1-1:
      kind: juniper_vjunosswitch
      group: tier-1
    node1-2:
      kind: juniper_vjunosswitch
      group: tier-1
    node2-1:
      kind: juniper_vjunosswitch
      group: tier-2
    node2-2:
      kind: juniper_vjunosswitch
      group: tier-2
  links:
  - endpoints:
    - node1-1:%!(EXTRA uint=1)
    - node2-1:%!(EXTRA uint=1)
    deploymentstate: 0
  - endpoints:
    - node1-1:%!(EXTRA uint=2)
    - node2-2:%!(EXTRA uint=1)
    deploymentstate: 0
  - endpoints:
    - node1-2:%!(EXTRA uint=1)
    - node2-1:%!(EXTRA uint=2)
    deploymentstate: 0
  - endpoints:
    - node1-2:%!(EXTRA uint=2)
    - node2-2:%!(EXTRA uint=2)
    deploymentstate: 0
debug: false
```

```
root@ubuntu:~/clab# containerlab generate --name 2tier --kind ceos --nodes 2,2
name: 2tier
prefix: null
mgmt: {}
settings: null
topology:
  nodes:
    node1-1:
      kind: ceos
      group: tier-1
    node1-2:
      kind: ceos
      group: tier-1
    node2-1:
      kind: ceos
      group: tier-2
    node2-2:
      kind: ceos
      group: tier-2
  links:
  - endpoints:
    - node1-1:eth1
    - node2-1:eth1
    deploymentstate: 0
  - endpoints:
    - node1-1:eth2
    - node2-2:eth1
    deploymentstate: 0
  - endpoints:
    - node1-2:eth1
    - node2-1:eth2
    deploymentstate: 0
  - endpoints:
    - node1-2:eth2
    - node2-2:eth2
    deploymentstate: 0
debug: false

root@ubuntu:~/clab#
```

**Comment by hellt** [comment]
Hi

can you please try deploying this topology:

```yaml
name: 2tier
prefix: null
mgmt: {}
settings: null
topology:
  nodes:
    node1-1:
      kind: juniper_vjunosswitch
      group: tier-1
    node1-2:
      kind: juniper_vjunosswitch
      group: tier-1
    node2-1:
      kind: juniper_vjunosswitch
      group: tier-2
    node2-2:
      kind: juniper_vjunosswitch
      group: tier-2
  links:
  - endpoints:
    - node1-1:et-0/0/1
    - node2-1:et-0/0/1
    deploymentstate: 0
  - endpoints:
    - node1-1:et-0/0/2
    - node2-2:et-0/0/1
    deploymentstate: 0
  - endpoints:
    - node1-2:et-0/0/1
    - node2-1:et-0/0/2
    deploymentstate: 0
  - endpoints:
    - node1-2:et-0/0/2
    - node2-2:et-0/0/2
    deploymentstate: 0
debug: false
```

I am working on a fix in the meanwhile
