### ISSUE TITLE
Add NO_PROXY env var to the lab nodes by default

### ISSUE THREAD

**Issue by hellt** [srl-labs/containerlab#2350]
When http proxy is in place to access internet resources containerlab users typically have to set the http_proxy/https_proxy env vars in their topologies to make the applications running in the containers use the proxy:

```yaml
name: anysec-macsec

mgmt:
  network: anysec
  ipv4-subnet: 172.50.50.0/24

topology:
  kinds:
    linux:
      image: ghcr.io/srl-labs/network-multitool
      env:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: pe1,pe2,p3,p4,ce5,ce6,client7,client8,gnmic,prometheus,grafana,localhost,172.50.50.0/24
```

Note, how every lab node, lab mgmt network and localhost has to be called out in the `no_proxy` env var to ensure that the nodes when communicating with each other will not try to reach the proxy.

Containerlab should set these values automatically as a default env var set:

- all node names as provided in the topology
- mgmt network
- localhost
- 127.0.0.1
- *.local addresses
