### ISSUE TITLE
Unable to start vmx

### ISSUE THREAD

**Issue by dmulyalin** [srl-labs/containerlab#2353]
Used [this guide](https://github.com/hellt/vrnetlab/blob/master/vmx/README.md) to build vmx image but unable to start it getting error:

```
root@salt:/home/user/containerlab# docker logs -f clab-network-lab-vmx-1
Traceback (most recent call last):
  File "/launch.py", line 12, in <module>
    import vrnetlab
  File "/vrnetlab.py", line 860, in <module>
    def cidr_to_ddn(prefix: str) -> list[str]:
TypeError: 'type' object is not subscriptable
```

topology file:

```
name: network-lab

topology:
  nodes:
    vmx-1:
      kind: juniper_vmx
      image: vrnetlab/juniper_vmx:21.4R1.12
      mgmt-ipv4: 172.100.100.15
      ports:
        - 2205:22
        - 8805:80
        - 8305:830

    
mgmt:
  network: network_lab_mgmt    # management network name
  ipv4-subnet: 172.100.100.0/24       # ipv4 range
```

also tried `vmx-bundle-23.2R2-S1.3` vmx version, still getting same error.

Containerlab version

```
root@vm:/home/user/containerlab# containerlab version
  ____ ___  _   _ _____  _    ___ _   _ _____ ____  _       _     
 / ___/ _ \| \ | |_   _|/ \  |_ _| \ | | ____|  _ \| | __ _| |__  
| |  | | | |  \| | | | / _ \  | ||  \| |  _| | |_) | |/ _` | '_ \ 
| |__| |_| | |\  | | |/ ___ \ | || |\  | |___|  _ <| | (_| | |_) |
 \____\___/|_| \_| |_/_/   \_\___|_| \_|_____|_| \_\_|\__,_|_.__/ 

    version: 0.60.1
     commit: 37adecb8
       date: 2024-12-07T19:58:41Z
     source: https://github.com/srl-labs/containerlab
 rel. notes: https://containerlab.dev/rn/0.60/#0601
root@salt:/home/user/containerlab#
```

running on ubuntu vm:

```
root@vm:/home/user/containerlab# hostnamectl
 Static hostname: vm
       Icon name: computer-vm
         Chassis: vm
      Machine ID: 03c522aef54a44ec8ed60f1738fe8564
         Boot ID: ed2fade4018749a8b41557bf0a0f0b8d
  Virtualization: vmware
Operating System: Ubuntu 22.04.2 LTS              
          Kernel: Linux 5.15.0-127-generic
    Architecture: x86-64
 Hardware Vendor: VMware, Inc.
  Hardware Model: VMware Virtual Platform
root@salt:/home/user/containerlab# 
```

Wondering what could be the issue, did anybody seen that before?
