### ISSUE TITLE
sonic 4node connectivity issue with links numbers >= 11

### ISSUE THREAD

**Issue by sudurais** [srl-labs/containerlab#2369]
When using SONiC VM, LLDP works correctly on interfaces with numbers below 11 (e.g., eth1, eth2, ...). However, for interfaces with numbers 11 or above (e.g., eth11, eth12), LLDP does not come up. Could be related how veth and sonic interface's mapped?

below non working topo. 
```
name: 4node

topology:
  nodes:
    sonic-1:
      kind: sonic-vm
      image: vrnetlab/sonic_sonic-vs:2024.05
      startup-config: /home/ubuntu/ws/4node/vs/configs/sonic/sonic-1.json
      cpu: 4
      memory: 4GB

    sonic-2:
      kind: sonic-vm
      image: vrnetlab/sonic_sonic-vs:2024.05
      startup-config: /home/ubuntu/ws/4node/vs/configs/sonic/sonic-2.json
      cpu: 4
      memory: 4GB

    sonic-3:
      kind: sonic-vm
      image: vrnetlab/sonic_sonic-vs:2024.05
      startup-config: /home/ubuntu/ws/4node/vs/configs/sonic/sonic-3.json
      cpu: 4
      memory: 4GB

    sonic-4:
      kind: sonic-vm
      image: vrnetlab/sonic_sonic-vs:2024.05
      startup-config: /home/ubuntu/ws/4node/vs/configs/sonic/sonic-4.json
      cpu: 4
      memory: 4GB

  links:
    - endpoints: ["sonic-1:eth1", "sonic-3:eth11"]
    - endpoints: ["sonic-1:eth2", "sonic-4:eth11"]
    - endpoints: ["sonic-2:eth1", "sonic-3:eth12"]
    - endpoints: ["sonic-2:eth2", "sonic-4:eth12"]

mgmt:
  network: clab

------
admin@sonic:~$ show lldp table
Capability codes: (R) Router, (B) Bridge, (O) Other
LocalPort    RemoteDevice    RemotePortID    Capability    RemotePortDescr
-----------  --------------  --------------  ------------  -----------------
--------------------------------------------------
Total entries displayed:  0
admin@sonic:~$
```

works fine when links numbers <= 10

  links:
    - endpoints: ["nqa3-7060DX5-D4-21:eth1", "nqa3-7060DX5-D4-17:eth9"]
    - endpoints: ["nqa3-7060DX5-D4-21:eth2", "nqa3-7060DX5-D4-19:eth9"]
    - endpoints: ["nqa3-7060DX5-D4-23:eth1", "nqa3-7060DX5-D4-17:eth10"]
    - endpoints: ["nqa3-7060DX5-D4-23:eth2", "nqa3-7060DX5-D4-19:eth10"]
    
    
```
admin@sonic:~$ show lldp table
Capability codes: (R) Router, (B) Bridge, (O) Other
LocalPort    RemoteDevice        RemotePortID       Capability    RemotePortDescr
-----------  ------------------  -----------------  ------------  -----------------
Ethernet32   sonic-1             22:ca:be:42:87:e0  BR            Ethernet0
Ethernet36   sonic-2             22:80:3c:07:85:4e  BR            Ethernet0
--------------------------------------------------
Total entries displayed:  2
admin@sonic:~
```

version
```
$ sudo containerlab version
  ____ ___  _   _ _____  _    ___ _   _ _____ ____  _       _
 / ___/ _ \| \ | |_   _|/ \  |_ _| \ | | ____|  _ \| | __ _| |__
| |  | | | |  \| | | | / _ \  | ||  \| |  _| | |_) | |/ _` | '_ \
| |__| |_| | |\  | | |/ ___ \ | || |\  | |___|  _ <| | (_| | |_) |
 \____\___/|_| \_| |_/_/   \_\___|_| \_|_____|_| \_\_|\__,_|_.__/

    version: 0.60.1
     commit: 37adecb8
       date: 2024-12-07T19:58:41Z
     source: https://github.com/srl-labs/containerlab
 rel. notes: https://containerlab.dev/rn/0.60/#0601
```
