### ISSUE TITLE
Tailscale for lab nodes

### ISSUE THREAD

**Issue by hellt** [srl-labs/containerlab#2396]
Add support for nodes to appear on tailnet of a user running the lab

**Comment by kaelemc** [comment]
somewhat related.. 

I was exploring how we can connect a clab to a physical lab, without having a port perma open etc.

So I made this thing in golang which just forward L2oUDPoTailscale.. not the cleanest but after a few days I finally got something working (right now it's very rudimentary, need to fix lots of stuff.. memory, port ranges etc.)

https://github.com/kaelemc/L2oTS

Topology looks like this.. the UDP port is simply derived from the digits of the interface..

```yaml
name: test
topology:
  nodes:
    srl-wlg:
      kind: nokia_srlinux
      image: ghcr.io/nokia/srlinux:24.10
    ts-wlg:
      kind: linux
      image: ghcr.io/kaelemc/l2ots:dev
      env:
        AUTH_KEY: tskey-auth-<redacted>
        PEER: ts-akl # magicDNS name or IP of node
        DEBUG: yaml

  links:
    - endpoints: [ts-wlg:eth1, srl-wlg:e1-1]
```
