### ISSUE TITLE
using dummy links (or links with a single endpoint) break export template logic

### ISSUE THREAD

**Issue by hellt** [srl-labs/containerlab#2480]
When using the link definition that has only one endpoint, the export template logic breaks.

Consider the following topo:

```yaml
name: test
topology:
  kinds:
    linux:
      image: alpine:3
  nodes:
    node1:
      kind: linux
  links:
    - type: dummy
      endpoint:
        node: node1
        interface: eth1
```

This raises a warning like:

```
21:08:52 WARN Cannot parse export template : template: export:50:18: executing "export" at <index $eps 1>: error calling index: reflect: slice index out of range
```

The template logic wants to have a 2nd endpoint and does not handle the error https://github.com/srl-labs/containerlab/blob/main/clab/export_templates/auto.tmpl
