### ISSUE TITLE
net.ipv6.conf.eth2.forwarding = 0

### ISSUE THREAD

**Issue by BurlyLuo** [srl-labs/containerlab#2536]
```
[root@rowan> 10-GRE]# clab version 
  ____ ___  _   _ _____  _    ___ _   _ _____ ____  _       _     
 / ___/ _ \| \ | |_   _|/ \  |_ _| \ | | ____|  _ \| | __ _| |__  
| |  | | | |  \| | | | / _ \  | ||  \| |  _| | |_) | |/ _` | '_ \ 
| |__| |_| | |\  | | |/ ___ \ | || |\  | |___|  _ <| | (_| | |_) |
 \____\___/|_| \_| |_/_/   \_\___|_| \_|_____|_| \_\_|\__,_|_.__/ 

    version: 0.62.0
     commit: d7588f9b
       date: 2025-01-17T10:30:15Z
     source: https://github.com/srl-labs/containerlab
 rel. notes: https://containerlab.dev/rn/0.62/
[root@rowan> 10-GRE]# 
```

```
[root@rowan> 10-GRE]# cat 1-manual-common-gre/2-setup-env-ipv6.sh 
#!/bin/bash
set -v
cat <<EOF>clab.yaml | clab deploy -t clab.yaml -
name: gre-ipv6
topology:
  nodes:
    gwx:
      kind: linux
      image: 192.168.2.100:5000/nettool
      exec:
      - ip a a 10.1.5.1/24 dev net1
      - ip a a 10.1.8.1/24 dev net2

    gre1:
      kind: linux
      image: 192.168.2.100:5000/nettool
      exec:
      - ip a a 10:244:1::1/64 dev eth1
      - ip addr add 10.1.5.10/24 dev eth2

      - ip l a gre00 type gre local 10.1.5.10 remote 10.1.8.10
      - ip l s gre00 up
      - ip a a 1:1:1::1/64 dev gre00
     
      - ip r a 10:244:2::/64 via 1:1:1::2 dev gre00 onlink

      - ip route replace default via 10.1.5.1 dev eth2 

    gre2:
      kind: linux
      image: 192.168.2.100:5000/nettool
      exec:
      - ip a a 10:244:2::1/64 dev eth1
      - ip addr add 10.1.8.10/24 dev eth2

      - ip l a gre00 type gre local 10.1.8.10 remote 10.1.5.10
      - ip l s gre00 up
      - ip a a 1:1:1::2/64 dev gre00

      - ip r a 10:244:1::/64 via 1:1:1::1 dev gre00 onlink

      - ip route replace default via 10.1.8.1 dev eth2


    server1:
      kind: linux
      image: 192.168.2.100:5000/nettool
      exec:
      - ip addr add 10:244:1::10/64 dev net0
      - ip route replace default via 10:244:1::1

    server2:
      kind: linux
      image: 192.168.2.100:5000/nettool
      exec:
      - ip addr add 10:244:2::10/64 dev net0
      - ip route replace default via 10:244:2::1

  links:
    - endpoints: ["gre1:eth1", "server1:net0"]
    - endpoints: ["gre2:eth1", "server2:net0"]

    - endpoints: ["gre1:eth2", "gwx:net1"]
    - endpoints: ["gre2:eth2", "gwx:net2"]
    
EOF

```

but

```
gre2~$sysctl -a | grep ipv6 | grep forw
sysctl: error reading key 'net.ipv6.conf.all.stable_secret': I/O error
sysctl: error reading key 'net.ipv6.conf.default.stable_secret': I/O error
sysctl: error reading key 'net.ipv6.conf.erspan0.stable_secret': I/O error
net.ipv6.conf.all.forwarding = 0
net.ipv6.conf.all.mc_forwarding = 0
net.ipv6.conf.default.forwarding = 0
net.ipv6.conf.default.mc_forwarding = 0
net.ipv6.conf.erspan0.forwarding = 0
net.ipv6.conf.erspan0.mc_forwarding = 0
sysctl: error reading key 'net.ipv6.conf.eth0.stable_secret': I/O error
net.ipv6.conf.eth0.forwarding = 0
net.ipv6.conf.eth0.mc_forwarding = 0
sysctl: error reading key 'net.ipv6.conf.eth1.stable_secret': I/O error
sysctl: error reading key 'net.ipv6.conf.eth2.stable_secret': I/O error
sysctl: error reading key 'net.ipv6.conf.gre00.stable_secret': I/O error
sysctl: error reading key 'net.ipv6.conf.gretap0.stable_secret': I/O error
sysctl: error reading key 'net.ipv6.conf.lo.stable_secret': I/O error
net.ipv6.conf.eth1.forwarding = 0
net.ipv6.conf.eth1.mc_forwarding = 0
net.ipv6.conf.eth2.forwarding = 0
net.ipv6.conf.eth2.mc_forwarding = 0
net.ipv6.conf.gre00.forwarding = 0
net.ipv6.conf.gre00.mc_forwarding = 0
net.ipv6.conf.gretap0.forwarding = 0
net.ipv6.conf.gretap0.mc_forwarding = 0
net.ipv6.conf.lo.forwarding = 0
net.ipv6.conf.lo.mc_forwarding = 0
gre2~$exit
exit
```

**Comment by hellt** [comment]
check what happens if you create a linux container with `docker` and use the same commands in it

**Comment by BurlyLuo** [comment]
```
[root@rowan> ~]# ds
CONTAINER ID   IMAGE                        COMMAND                  STATUS         NAMES
6cd7aae464b5   192.168.2.100:5000/nettool   "/sbin/tini -g -- /e…"   Up 4 seconds   awesome_leakey
[root@rowan> ~]# docker exec -it awesome_leakey bash 
6cd7aae464b5~$ip a 
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
3: gre0@NONE: <NOARP> mtu 1476 qdisc noop state DOWN group default qlen 1000
    link/gre 0.0.0.0 brd 0.0.0.0
4: gretap0@NONE: <BROADCAST,MULTICAST> mtu 1462 qdisc noop state DOWN group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
5: erspan0@NONE: <BROADCAST,MULTICAST> mtu 1450 qdisc noop state DOWN group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
228: eth0@if229: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:ac:11:00:02 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.17.0.2/16 brd 172.17.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 172:17:0:1:0:242:ac11:2/64 scope global nodad 
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe11:2/64 scope link 
       valid_lft forever preferred_lft forever
6cd7aae464b5~$
6cd7aae464b5~$ sysctl net.ipv6.conf.all.forwarding
net.ipv6.conf.all.forwarding = 0
6cd7aae464b5~$ sysctl net.ipv6.conf.eth0.forwarding
net.ipv6.conf.eth0.forwarding = 0
6cd7aae464b5~$exit
exit
[root@rowan> ~]# sysctl net.ipv6.conf.all.forwarding
net.ipv6.conf.all.forwarding = 1
[root@rowan> ~]# 
```
Yes, the default is 0.

my view is can we set a flag to set to 1 as default
```
    gre2:
      kind: linux
      image: 192.168.2.100:5000/nettool
      exec:
      - ip a a 10:244:2::1/64 dev eth1
      - ip addr add 10.1.8.10/24 dev eth2

      - ip l a gre00 type gre local 10.1.8.10 remote 10.1.5.10
      - ip l s gre00 up
      - ip a a 1:1:1::2/64 dev gre00

      - ip r a 10:244:1::/64 via 1:1:1::1 dev gre00 onlink

      - ip route replace default via 10.1.8.1 dev eth2
      
      - bash -c "sysctl -w net.ipv6.conf.all.forwarding=1"

```
