### ISSUE TITLE
clabernetes-ui not displaying all the links

### ISSUE THREAD

**Issue by fahadnaeemkhan** [srl-labs/containerlab#2590]
Apologies for posting it here but i couldn't the repo for `clabernetes-ui`. Is it not open-source?

# Topology

Basic https://github.com/srl-labs/srlinux-getting-started topology

```yaml
      topology:
        kinds:
          nokia_srlinux:
            image: ghcr.io/nokia/srlinux
            image-pull-policy: Always
          linux:
            image: ghcr.io/srl-labs/network-multitool
            image-pull-policy: Always

        nodes:
          leaf1:
            kind: nokia_srlinux
            type: ixrd2l
            image-pull-policy: Always
          leaf2:
            kind: nokia_srlinux
            type: ixrd2l
            image-pull-policy: Always
          spine1:
            kind: nokia_srlinux
            type: ixrd5
            image-pull-policy: Always
          client1:
            kind: linux
            image-pull-policy: Always
            exec:
              - ip link set address 00:c1:ab:00:00:01 dev eth1
              - ip addr add 192.168.0.1/24 dev eth1
          client2:
            kind: linux
            image-pull-policy: Always
            exec:
              - ip link set address 00:c1:ab:00:00:02 dev eth1
              - ip addr add 192.168.0.2/24 dev eth1


        links:
          # inter-switch links
          - endpoints: ["leaf1:e1-49", "spine1:e1-1"]
          - endpoints: ["leaf2:e1-49", "spine1:e1-2"]
          # client links
          - endpoints: ["client1:eth1", "leaf1:e1-1"]
          - endpoints: ["client2:eth1", "leaf2:e1-1"]
```

# UI

<img width="914" alt="Image" src="https://github.com/user-attachments/assets/65e5a2f7-0218-4a49-ac43-5a61d16f511d" />
