### ISSUE TITLE
Race between entrypoint execution and links creation

### ISSUE THREAD

**Issue by jcpvdm** [srl-labs/containerlab#2632]
It seems that container links creation and execution of container `entrypoint` is done concurrently. If the code in `entrypoint` depends on links and is executed first then errors will happen, leaving the container deployment incomplete:

**docker logs**
```
Cannot find device "eth1"
Device "eth1" does not exist.
Cannot find device "eth2"
Device "eth2" does not exist.
Cannot find device "eth3"
Device "eth3" does not exist.
Failed to enslave eth1 to bond0. Is bond0 ready and a bonding interface ?
Failed to enslave eth2 to bond0. Is bond0 ready and a bonding interface ?
Failed to enslave eth3 to bond0. Is bond0 ready and a bonding interface ?
```
in this case, bond0 will miss its member links due to the errors

**clab topology yml**
```
name: teste
topology:
  defaults:
    kind: linux
    image: ghcr.io/srl-labs/network-multitool:latest
  kinds:
    nokia_srlinux:
      image: ghcr.io/nokia/srlinux:24.10.4
      stages:
        create:
          wait-for:
            - node: client12
              stage: configure
    linux:
      image: ghcr.io/srl-labs/network-multitool:latest
      startup-delay: 10
      env:
        http_proxy: $http_proxy
        https_proxy: $https_proxy
        no_proxy: $no_proxy

  nodes:
    client12:
        kind: linux
        group: dcclient
        image: ghcr.io/srl-labs/network-multitool
        binds:
           - interfaces-test:/etc/network/interfaces

    leaf11:
      kind: nokia_srlinux
      type: ixrd2l
      group: leaf
      startup-config: configs/srl/__clabNodeName__.cfg

    leaf12:
      kind: nokia_srlinux
      type: ixrd2l
      group: leaf
      startup-config: configs/srl/__clabNodeName__.cfg

    leaf13:
      kind: nokia_srlinux
      type: ixrd2l
      group: leaf
      startup-config: configs/srl/__clabNodeName__.cfg

  links:
    - endpoints: ["leaf11:e1-2", "client12:eth1"]
    - endpoints: ["leaf12:e1-2", "client12:eth2"]
    - endpoints: ["leaf13:e1-2", "client12:eth3"]
```

**interfaces-test**
```
auto lo
iface lo inet loopback

auto bond0

iface bond0
    use bond
    hwaddress 00:c1:00:dc:01:12
    mtu 9500
    bond-slaves eth1 eth2 eth3
    bond-mode 802.3ad
    bond-miimon 100
    bond-xmit-hash-policy layer3+4
    bond-min-links 1
    bond-lacp-rate fast
    bond-updelay 200

# VLAN 1
auto bond0.1
iface bond0.1
    requires bond0
    address 10.64.30.12/24
    address fd00:fde8:0:30::12/64
    post-up ip r a 10.0.0.0/8 via 10.64.30.1 dev bond0.1
    post-up ip -6 r a fd00:fde8::/32 via fd00:fde8:0:30::1 dev bond0.1

# VLAN 101
auto bond0.101
iface bond0.101
    requires bond0
    address 192.168.30.12/24
    address fd00:ffdd:0:30::12/64
    post-up ip r a 192.168.0.0/16 via 192.168.30.1 dev bond0.101
    post-up ip -6 r a fd00:ffdd::/32 via fd00:ffdd:0:30::1 dev bond0.101
```

**network-multitool entrypoint**
```
ifup -a
#########
# create directories for ssh host keys
mkdir -p /etc/dropbear
# create the host keys
dropbearkey -t rsa -f /etc/dropbear/dropbear_rsa_host_key 2048
dropbearkey -t ecdsa -f /etc/dropbear/dropbear_ecdsa_host_key 512
dropbearkey -t ed25519 -f /etc/dropbear/dropbear_ed25519_host_key
# and start the process
/usr/sbin/dropbear -j -k -E -F &
#########
# Execute the command specified as CMD in Dockerfile:
exec "$@"
```

A workaround is to add a sleep before `ifup -a` in the entrypoint, but I wonder if there is a better way to ensure that entrypoint is executed only after the clab-created links.

**Environment**:  
Linux distro: Rocky Linux 9.6 (Blue Onyx)
Linux Kernel: 5.14.0-570.22.1.el9_6.x86_64
Docker Engine: 28.1.1
Clab version: 0.68.0

**Comment by steiler** [comment]
Yeah I'm afraid you have to edit your entrypoint. Instead of a general sleep I'd add a specific check for the condition you depend on with a sleep to not saturate the cpu.
Or you remove the entrypoint and make it execute after link creation phase.

https://containerlab.dev/manual/nodes/#per-stage-command-execution
```
nodes:
  node1:
    stages:
      create-links:
        exec:
          - command: <path-to-entrypoint>
            target: container 
            phase: on-exit
```
