### ISSUE TITLE
check that across bridge interfaces there are no duplicates

### ISSUE THREAD

**Issue by hellt** [srl-labs/containerlab#387]
the following links definition will fail at runtime, since two bridges reference the same interface `eth1`.

```yaml
# br1 and br2 are bridges
links:
- endpoints: ["br1:eth1", "spine1:e1-1"]
- endpoints: ["br2:eth1", "spine2:e1-1"]
```

A check is needed to get all interfaces of all bridges and check that none of them repeat
