### ISSUE TITLE
Add option to specify the name of the management interface for cEOS

### ISSUE THREAD

**Issue by teunvink** [srl-labs/containerlab#389]
On physical Arista EOS switches, the default management interface is called 'Management1'. cEOS containers are generated with 'Management0' as the management interface name. I'd like to be able to specify this name (or switch it to Management1 in some other way) so that I can run my ansible playbooks for my physical (production) switches on my test containers in containerlab as well without modifying them.

I assume this would be a feature request, but if there's already a way to do this that I missed I'd be more than happy to hear so.

**Comment by karimra** [comment]
Hi, 

You can edit the default cEOS config template, but it will be overwritten on next upgrade.
It should be located under `/etc/containerlab/templates/arista/`
Change `interface Management0` to `interface Management1`


```
hostname {{ .ShortName }}
username admin privilege 15 secret admin
!
service routing protocols model multi-agent
!
interface Management0 
{{ if .MgmtIPv4Address }}ip address {{ .MgmtIPv4Address }}/{{.MgmtIPv4PrefixLength}}{{end}}
{{ if .MgmtIPv6Address }}ipv6 address {{ .MgmtIPv6Address }}/{{.MgmtIPv6PrefixLength}}{{end}}
!
management api gnmi
   transport grpc default
!
management api netconf
   transport ssh default
!
management api http-commands
   no shutdown
!
end
```

Or you could set a custom template ( written in [Go Text Template](https://golang.org/pkg/text/template/) ), per kind or per node, in your lab file:

```yaml
topology:
  kinds:
    ceos:
      config: /path/to/custom_ceos.cfg ## <- applies to all nodes with kind ceos
  nodes:
    node1:  
      kind: ceos
      config: /path/to/my/template.cfg ## <- overwrites the config under topology.kinds.ceos.config
```
