### ISSUE TITLE
Configuration artifacts location

### ISSUE THREAD

**Issue by networkop** [srl-labs/containerlab#394]
I find it a bit confusing how the path is determined for node's artefacts. 
For example ` Containerlab will name directories after the node names and will only created those if they are needed. For instance, by default any node of kind linux will not have it's own directory under the Lab Directory`  doesn't make any sense. why make linux node type special?

Another confusing bit is the bind mounts location. It looks like the path is always relative to the `cwd` with the lab yaml file, however [other artefacts](https://containerlab.srlinux.dev/manual/conf-artifacts/) are mounted from their own directories. Wouldn't it make sense to standardize the behaviour for all of them? unless there's an underlying reason I don't understand.

**Comment by hellt** [comment]
> doesn't make any sense. why make linux node type special?

since nodes of `linux` kind don't currently have any artifacts (such as startup config, or certificates), nor state, there is no need to create a node directory for them. Hence this note.



> Another confusing bit is the bind mounts location. It looks like the path is always relative to the `cwd` with the lab yaml file, however [other artefacts](https://containerlab.srlinux.dev/manual/conf-artifacts/) are mounted from their own directories

I am not sure I follow here. In the [binds](https://containerlab.srlinux.dev/manual/nodes/#binds) section you are free to use any path such as:

- absolute path: `/a/b/c.txt`
- relative to the $pwd path: `b/c.txt` or `./b/c.txt`
- home path: `~/c.txt`

The [conf artifacts](https://containerlab.srlinux.dev/manual/conf-artifacts/) doc explains which artifacts containerlab will usually put for some nodes under which names. But they are orthogonal to the bind mounts, since bind mounts are not copied over to the node directory

**Comment by hellt** [comment]
I have the impression that when a certain level of tailoring is needed, and the NOS you're working on is of potential interest to a wider community, then it makes sense to work on building a kind for that.

With such, anything peculiar that this kind might need can be nicely abstracted in the code, so a user won't have to even bother

**Comment by networkop** [comment]
yep, once the cumulus image is ready, I'll do a PR for it to add a new kind for it. 
but this issue is still relevant. I don't understand why `config` and `bind` paths are processed differently. Both are designed to map some host OS files inside the container and both would benefit from a node-specific directory. Here's an example. First this is how I'm mapping configuration files now:
```
topology:
  nodes:
    leaf1:
      kind: linux
      image: cx:latest
      binds:
      - leaf1/daemons:/etc/frr/daemons
      - leaf1/frr.conf:/etc/frr/frr.conf
```
Note the `leaf1` prefix I have to add to make sure each node gets its unique config. Now image if binds were assumed to be taken from a `<lab_dir>/<node_nam>` dir, I could then re-write it to look like this:
```
topology:
  nodes:
    leaf1:
      kind: linux
      image: cx:latest
      binds:
      - daemons:/etc/frr/daemons
      - frr.conf:/etc/frr/frr.conf
```
And if #391  is implemented, this will become even better:

```
topology:
  kind:
    cumulus:
      image: cx:latest
      binds:
      - daemons:/etc/frr/daemons
      - frr.conf:/etc/frr/frr.conf
  nodes:
    leaf1:
      kind: cumulus
   leaf2:
      kind: cumulus
```

There's also a wider issue about `config` being a "special" kind of mount. I'd argue that it's easier to have just one standard way to map files inside containers and stick to just that.

**Comment by hellt** [comment]
`binds` behave the same way as `--volume` in docker CLI or in `docker-compose` does it not?

And `config` behaves the same way, when you refer a `config` file it just happens to be copied over to the node dir to persist there instead of being mounted from some host location and be overwritten by any changes made inside the container.

In other words, there is no such user-facing bind configuration in containerlab that takes a path relative to node directory.
One of the reasons being that typically users to do not put files under the nodes directories (with a small exception for root-ca), it is containerlab' task to put the necessary files over.

So yes, the envisioned way to bind **node-specific** files is to do something like that:

```yaml
topology:
  nodes:
    leaf1:
      kind: linux
      image: cx:latest
      binds:
      - ~/lab-cfgs/leaf1/daemons:/etc/frr/daemons
      - ~/lab-cfgs/leaf1/frr.conf:/etc/frr/frr.conf
    leaf2:
      kind: linux
      image: cx:latest
      binds:
      - ~/lab-cfgs/leaf2/daemons:/etc/frr/daemons
      - ~/lab-cfgs/leaf2/frr.conf:/etc/frr/frr.conf
```

**Comment by networkop** [comment]
but you do see how verbose it is, don't you? whereas it's easy to check that if the bind path is not absolute, then look in the node-specific directory instead of the lab directory. You can store those bind files in node-specific directories for the same reason you store config in there - persistence, protection from overwriting. 
Effectively, what I'm saying, bind mounts are the same thing as the config. Interface configuration file? - a config. Certificate files? - also a config. So it would only make sense to treat them in the same way.

**Comment by hellt** [comment]
So you are saying that the following path-search patterns will suffice? 

- `a.txt` - will be looked up in the node dir
- `./a.txt` - will be looked up in the CWD (rel path)
- `~/a.txt` - will be looked up in `$HOME/a.txt`
- `/a.txt` - will be looked at abs path specified

**Comment by networkop** [comment]
yes, I'd even collapse the first two, to make it easier. So just have two options:
1. Absolute path - no change
2. Non-absolute path - join with `nodeDir`

**Comment by hellt** [comment]
I am afraid we can't collapse the first two
what if you have the following structure

```
lic.txt
lab.clab.yml
```

and you want to bind mount the `lic.txt`? You can't use the abs path, since you don't want your users who will clone your lab to change the abs paths as per their environment. So relative path to the cwd makes sense to keep

**Comment by networkop** [comment]
you could put `lic.txt` in every `<labName>/<nodeName>` dir?
we don't want to make things unnecessarily complex.

**Comment by hellt** [comment]
> you could put lic.txt in every <labName>/<nodeName> dir?
now that seems verbose in my world =) You then need to update it every now and then and if you do a destroy of a lab with state cleanup the labdir will get deleted will all the things inside it.

I must mention here that so far we haven't seen a case when users needed to populate node dirs themselves.

Maybe what can be done is a special marker for a case when user expects containerlab to lookup a node dir: `$nodeDir/a.txt`.
This makes it explicit, while keeping contract of using the "normal" path resolution for binds

**Comment by kellerza** [comment]
I also understood the `nodeDir` as a temporary location, created by *deploy* and later deleted by *destroy*.

All relative paths should be wrt the topo file in my view, as this is the key anchor point. It's what you want to deploy.
Absolute paths just makes everything less portable.

If you want to protect these bind files from being written to, the only way I see is for *deploy* to copy it to the nodeDir and change the bindline to point to the copy. It wont be any less verbose though @networkop , since the bindline in the topo file needs to point to the original file.

**Comment by hellt** [comment]
just keep in mind that `destroy` will not remove the Lab Dir, unless `--cleanup` flag is provided.

The same effect is when we do `deploy --reconfigure`.

In my view there is a benefit of making clab to look up NodeDir, but that shouldn't be at expense of re-defining the way relative path is treated, as this is confusing to a user.
I woudn't mind, though, to implement this:

```yaml
name: test
topology:
  nodes:
    leaf1:
      kind: linux
      image: cx:latest
      binds:
      - $nodeDir/daemons:/etc/frr/daemons # expands to ./clab-test-leaf1/daemons
      - $nodeDir/frr.conf:/etc/frr/frr.conf
    leaf2:
      kind: linux
      image: cx:latest
      binds:
      - $nodeDir/daemons:/etc/frr/daemons # expands to ./clab-test-leaf2/daemons
      - $nodeDir/frr.conf:/etc/frr/frr.conf
```

**Comment by networkop** [comment]
So if cleanup removes all of the nodeDirs, what's the indended way to supply startup configs? For example, if I were doing a training I'd want to ship the lab in a single archive and be able to spine it up, down, cleanup and still preserve the startup state.

**Comment by networkop** [comment]
I see both of your points, I now don't understand why config is sitting in this ephemeral directory.

**Comment by hellt** [comment]
> So if cleanup removes all of the nodeDirs, what's the indended way to supply startup configs? For example, if I were doing a training I'd want to ship the lab in a single archive and be able to spine it up, down, cleanup and still preserve the startup state.

you would do one of the two things:
1. store your config in a repo folder that is not Lab Dir and bind mount it like I showed [here](https://github.com/srl-labs/containerlab/issues/394#issuecomment-823830279). This way you keep startup config outside of the ephemeral lab directory
2. you would not use `destroy --cleanup`, and use just `destroy`. This will keep Lab Dir intact whereas will remove the containers. On a subsequent `deploy` the necessary files will be mounted from LabDir once again.



> I now don't understand why config is sitting in this ephemeral directory.

Historical reasons. Initially config was something that is always a product of generation out of the embedded templates. When I added user-specified config files I kept the same logic of copying over the product of templation to the NodeDir

**Comment by kellerza** [comment]
> My original confusion was caused by the fact the config and bind paths are treated differently.

`config:` is a first class clab citizen. The kind decides what to do with it. In most instances this is *startup config*, copied to the `nodeDir` and the the kind either binds the file to the container, maybe it binds a folder to the container, it might create a ftp/tftp server to expose the file (inside vr-xxx from what I've seen). But its kind-specific, typically copy & expose as the kind requires.

`binds:` is just a docker concept. The host to the container. No copying, nothing special. It's not a startup concept, not protected in any way. 

What I suggested above is a way to make `bind:` act more like its first class citizen cousin `config:`, but for all kinds.

**Comment by networkop** [comment]
yep, ok. I got it. I still find this idea of an ephemeral config dir confusing as the docs clearly [say](https://containerlab.srlinux.dev/manual/nodes/#config) that this is how you should mount your startup configuration.
And `config` also not gonna work if there are multiple directories where configuration files are stored, e.g. cumulus.

**Comment by kellerza** [comment]
Might be good to think how cumulus will use its config:. It might be a folder & you'll have to copy the entire "startup" folder to the nodeDir.

You will always need an ephemeral part, as its not ideal to have a *save* influence a new deployment. Except if that is the new startup, in which case you should copy it to startup (on the clab-host, not netconf 😃 )

**Comment by networkop** [comment]
the problem with cumulus and maybe some of the other Linux-based NOSs is that they don't store files in one place. In my case I've got two directories  - `/etc/frr` and `/etc/network/` .  How is this going to work with `config`?

**Comment by kellerza** [comment]
just a thought: if you specify the `/etc` in config, then the cumulus kind can decide to only mount 2 folders inside what you specified (/frr and /network)

**Comment by hellt** [comment]
> the problem with cumulus and maybe some of the other Linux-based NOSs is that they don't store files in one place. In my case I've got two directories - `/etc/frr` and `/etc/network/` . How is this going to work with `config`?

as @kellerza mentioned, in the embedded kind you have a liberty to define how you treat the information passed in `config`. 

You can, for example, make per-node dirs aka `configs/leaf{1..n}` and each dir will have folder or files that cumulus needs. Then in the kind init function you will check which files you need to mount to which paths inside the container. We do a similar thing for SR Linux.

With that you have a single dir that stores all the startup config of the node and it gets mounted to the paths specified by the logic in the kind code

**Comment by networkop** [comment]
yep, this will work. I'd still prefer _not_ to hardcode any paths inside the Go code. Simply because I may decide I only want to mount one file, or I may decide to control another, non-default service by mounting a config file. So having a config syntax similar to bind would make a lot more sense, e.g.
```
name: test
topology:
  nodes:
    leaf1:
      kind: linux
      config: 
      - foo.conf:/etc/foo/foo.conf
      - bar.conf:/etc/bar/bar.conf
    spine3:
      kind: linux
      config: 
      - baz.conf:/etc/baz/baz.conf
```

At which stage your `config` looks exactly like you `bind` definition.
