### ISSUE TITLE
introduce path variable `$nodeDir` that will expand to abs path of the node directory

### ISSUE THREAD

**Issue by hellt** [srl-labs/containerlab#398]
To support the use case expressed in #394 a path variable such as `$nodeDir` can be implemented to allow the lookup of the files located at node's directory.

This will make possible the following binds configuration:

```yaml
name: test
topology:
  nodes:
    leaf1:
      kind: linux
      image: cx:latest
      binds:
      - $nodeDir/daemons:/etc/frr/daemons # expands to ./clab-test-leaf1/daemons
      - $nodeDir/frr.conf:/etc/frr/frr.conf
    leaf2:
      kind: linux
      image: cx:latest
      binds:
      - $nodeDir/daemons:/etc/frr/daemons # expands to ./clab-test-leaf2/daemons
      - $nodeDir/frr.conf:/etc/frr/frr.conf
```
