### ISSUE TITLE
Install script installs RPM on Ubuntu: Error: The operation was canceled.

### ISSUE THREAD

**Issue by bbros-dev** [srl-labs/containerlab#438]
In [this](https://github.com/bbros-dev/netsim-tools/runs/2711095050?check_suite_focus=true) GitHub Action, defined as:

```yaml
name: Validate Data

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.6"
          - "3.9"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Run Mypy
        run: |
          mypy -p netsim
      - name: Run transformation tests
        run: |
          cd tests
          PYTHONPATH="../" pytest
      - name: Run ContainerLab tests
        run: |
          bash -c "$(curl -sL https://get-clab.srlinux.dev)" -- -v 0.14.3
          ./tests/containerlab/bats/bin/bats tests/containerlab/
```

We observe the log:

```
Run bash -c "$(curl -sL https://get-clab.srlinux.dev)" -- -v 0.14.3
Downloading https://github.com/srl-labs/containerlab/releases/download/v0.14.3/containerlab_0.14.3_linux_amd64.rpm
Preparing to install containerlab 0.14.3 from package
rpm: RPM should not be used directly install RPM packages, use Alien instead!
rpm: However assuming you know what you are doing...

                           _                   _       _     
                 _        (_)                 | |     | |    
 ____ ___  ____ | |_  ____ _ ____   ____  ____| | ____| | _  
/ ___) _ \|  _ \|  _)/ _  | |  _ \ / _  )/ ___) |/ _  | || \ 
( (__| |_|| | | | |_( ( | | | | | ( (/ /| |   | ( ( | | |_) )
\____)___/|_| |_|\___)_||_|_|_| |_|\____)_|   |_|\_||_|____/ 

version: 0.14.3
 commit: 0a42cfe
   date: 2021-05-28T10:19:14Z
 source: https://github.com/srl-labs/containerlab
1..4
Error: The operation was canceled.

```
