### ISSUE TITLE
containerlab deploy hangs on 

### ISSUE THREAD

**Issue by fire-ant** [srl-labs/containerlab#450]
Aside from some issues when upgrading containerlab from 0.13.0 to 0.14.0 I thought it best to mention that from 0.14.0 up that I see deployments failing. Specifically they debug log shows they hang:

stdout log:

```
DEBU[0001] containers created, retrieving state and IP addresses... 
DEBU[0001] enriching nodes with IP information...       
DEBU[0001] Running postdeploy actions for sonic-vs 'spine' node 
DEBU[0001] Running postdeploy actions for Linux 'client1' node 
DEBU[0001] Running postdeploy actions for Linux 'client2' node 
DEBU[0001] Running postdeploy actions for sonic-vs 'leaf1' node 
DEBU[0001] Running postdeploy actions for sonic-vs 'leaf2' node 
DEBU[0001] /clab-3_stage_clos-leaf1 exec created d3f701f21a0d49212019a25c2d6e55e00f6b8038fc3f46d2c58c9071fd1b6ca8 
DEBU[0001] /clab-3_stage_clos-leaf2 exec created cfb3427ba36d1027cb56d26a3b5c8bf14456689161fc54a13a361e91736134c8 
DEBU[0001] /clab-3_stage_clos-spine exec created d9e355cc6062789cc3b3e74c48dd6d4578f45986bb840ec1b5a88cc390f076fc 
DEBU[0001] /clab-3_stage_clos-spine exec attached d9e355cc6062789cc3b3e74c48dd6d4578f45986bb840ec1b5a88cc390f076fc 
DEBU[0001] /clab-3_stage_clos-leaf1 exec attached d3f701f21a0d49212019a25c2d6e55e00f6b8038fc3f46d2c58c9071fd1b6ca8 
DEBU[0001] /clab-3_stage_clos-leaf2 exec attached cfb3427ba36d1027cb56d26a3b5c8bf14456689161fc54a13a361e91736134c8 
DEBU[0002] /clab-3_stage_clos-spine exec created d9e355cc6062789cc3b3e74c48dd6d4578f45986bb840ec1b5a88cc390f076fc 
DEBU[0002] /clab-3_stage_clos-spine exec attached d9e355cc6062789cc3b3e74c48dd6d4578f45986bb840ec1b5a88cc390f076fc 
DEBU[0002] /clab-3_stage_clos-leaf2 exec created cfb3427ba36d1027cb56d26a3b5c8bf14456689161fc54a13a361e91736134c8 
DEBU[0002] /clab-3_stage_clos-leaf2 exec attached cfb3427ba36d1027cb56d26a3b5c8bf14456689161fc54a13a361e91736134c8 
DEBU[0002] /clab-3_stage_clos-leaf1 exec created d3f701f21a0d49212019a25c2d6e55e00f6b8038fc3f46d2c58c9071fd1b6ca8 
DEBU[0002] /clab-3_stage_clos-leaf1 exec attached d3f701f21a0d49212019a25c2d6e55e00f6b8038fc3f46d2c58c9071fd1b6ca8
```

topology.yaml:

```
topology:
  kinds:
    sonic-vs:
      type: p4
      image: docker-sonic-vs-ssh:latest
    linux:
      image: praqma/network-multitool
  nodes:
    leaf1:
      kind: sonic-vs
      type: p4
    leaf2:
      kind: sonic-vs
      type: p4
    spine:
      kind: sonic-vs
      type: p4
    client1:
      kind: linux
    client2:
      kind: linux

  links:
    - endpoints: ["leaf1:eth1", "spine:eth1"]
    - endpoints: ["leaf2:eth1", "spine:eth2"]

    - endpoints: ["client1:eth1", "leaf1:eth3"]
    - endpoints: ["client2:eth1", "leaf2:eth3"]
```

System:

```
$ docker -v
Docker version 20.10.6, build 370c289
$ uname -a
Linux frr-role-config-qm-lab 5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

I've pinned to 0.13.0 (which works for me) for the meantime. Let me know if there's anything else needed.
