### ISSUE TITLE
add `dns` list option for nodes to define DNS servers for container image

### ISSUE THREAD

**Issue by hellt** [srl-labs/containerlab#453]
ref: https://docs.docker.com/config/containers/container-networking/#dns-services

something like this

```yaml
node:
  dns:
    addr:
      - 1.1.1.1
      - 8.8.8.8
    opts:
      - bla
    search:
      - foo.com
```
