### ISSUE TITLE
add `macvlan` driver support to enable clab nodes to be exposed to a routable network a host is connected to

### ISSUE THREAD

**Issue by hellt** [srl-labs/containerlab#475]
To allow for clab nodes to be reachable from outside of the containerlab host a multiple techniques can be used.

Some of them are documented in [clab docs](https://containerlab.srlinux.dev/manual/multi-node/).

One of the ways that is not yet implemented in clab is to be able to use macvlan network for clab nodes. This can allow for clab nodes to appear to be connected to a host interface directly (a bridge interface or a physical nic interface) and thus be addressed from the same address space the interface is.

This can let systems and machines that has a route to a network that includes that host interface to reach the clab nodes launched with macvlan network type.

Read more about it here:
- https://docs.docker.com/network/macvlan/
- https://docs.docker.com/network/network-tutorial-macvlan/
- https://collabnix.com/2-minutes-to-docker-macvlan-networking-a-beginners-guide/

**Comment by steiler** [comment]
Close as Done? Or am I missing something here?

**Comment by hellt** [comment]
@steiler this is similar but different https://github.com/srl-labs/containerlab/issues/1393#issuecomment-1550867397

**Comment by steiler** [comment]
OK, yes I remember the discussion now.
Thanks

**Comment by jbernardini** [comment]
I've got a fork here that implements this: https://github.com/jbernardini/containerlab

It creates the macvlan network with updated types and schema support. I've built and tested in my environment and it's working. But the code needs refinement and I'd appreciate review and testing before I submit a PR.

I'm also working on creating the Containerlab host networking as per steps 2, 3, and 5 in my comment here: https://discord.com/channels/860500297297821756/860500297297821759/1400987584460755165 
But this part is still WIP and only for Linux though so this may be best left out, and done manually. Right now that's in docker.go and probably needs to be moved out into a separate host package, if retained.

mgmt topology block looks like this:
```
mgmt:
      network: clab-macvlan      # Name of the Docker network
      driver: macvlan            # Network driver: "bridge" (default) or "macvlan"
      macvlan-parent: ens192       # Parent interface (only for macvlan driver)
      macvlan-mode: bridge       # Macvlan mode (only for macvlan driver)
      ipv4-subnet: 192.168.1.0/24
      ipv4-gw: 192.168.1.1
      macvlan-aux: 192.168.1.254  # Reserved IP for host interface
```
