### ISSUE TITLE
ceos startup-config breaking post upgrade from 1.14.4 to 1.15.1

### ISSUE THREAD

**Issue by UchihaItachiSama** [srl-labs/containerlab#526]
- Node: `ceos - Arista cEOS`
- Version: 1.15.1
- Effected component: `startup-config` referenced in previous releases as `config`
- Trigger: Upgrade from 1.14.4 to 1.15.1

- Issue Details:
User defined configuration file using `startup-config` for a specific node in topology is effecting all nodes in the topology for cEOS node type post upgrade to 1.15.1 release train.

Prior to upgrade we were using `config` to specify user defined config for a specified node in the topology which was working fine.
```
leaf1a:
      kind: ceos
      image: ceosimage:4.26.1F
      mgmt_ipv4: 172.100.100.4
controller1:
      kind: ceos
      image: ceosimage:4.26.1F
      mgmt_ipv4: 172.100.100.8
      config: cvx_oob_template/controller1-startup.conf
```

With this only the `controller1` node was booting with the `controller1-startup.conf` configuration, and other nodes like `leaf1a` were booting using the default ceos template present at `/etc/containerlab/templates/arista/ceos.cfg.tpl`

post upgrade to 1.15.1 and updating `config` to `startup-config` I can see the user defined configuration file is effecting the config for other nodes in the topology.

```
INFO[0000] Parsing & checking topology file: topology.yaml
DEBU[0000] Lab name: aristacvxlab
INFO[0000] [DEBUG] generating config for node controller1 from file /home/babayaga/evpn-vxlan-examples/labs/cvx/direct_routing/cvx_oob_template/controller1-startup.conf
INFO[0000] Creating container: controller1
!
INFO[0000] hostname cvx1
!
```

but the same can be seen for other nodes as well in the topology:

```
INFO[0011] [DEBUG] generating config for node leaf1a from file
INFO[0011] [DEBUG] node 'leaf1a' generated config: ! Startup-config last modified at Mon Jul 12 11:05:57 2021 by admin
!
INFO[0011] hostname cvx1
!
```
 
Also, I understand the node templates have been embedded into the binary file now. Is there any other way to change/override the default templates as available earlier by changing the files under  `/etc/containerlab/templates/`?

**Comment by hellt** [comment]
thanks for reporting this, @UchihaItachiSama 
I will have a look

**Comment by hellt** [comment]
yep, there was a bug
I have created a beta build which I would like you to check out to see if this fixes your issue

you can install it with first removing the installed containerlab version (yum/apt remove containerlab) and then installing the beta build

```
bash -c "$(curl -sL https://get-clab.srlinux.dev)" -- -v 0.0.0-0.15.2-beta
```

As to the 2nd question on how to provide a default startup config template - this is now needs to be done via providing a startup template explicitly.
For example, here is the default ceos template that is now embedded in the binary - https://github.com/srl-labs/containerlab/blob/master/nodes/ceos/ceos.cfg

if you copy this file, modify as you need and save it under some name, for example `ceos-custom-startup.cfg`, then you can use it as a default startup for all `ceos` kind nodes with the following fields in the clab file:


```yaml
name: ceos

topology:
  kinds:
    ceos:
      startup-config: ceos-custom-startup.cfg
  nodes:
    # ceos1 will boot with ceos-custom-startup.cfg as set in the kind parameters
    ceos1:
      kind: ceos
      image: ceos:4.25.0F
    # ceos2 will boot with its own specific startup config, as it overrides the kind variables
    ceos2: 
      kind: ceos
      image: ceos:4.25.0F
      startup-config: node-specific-startup.cfg
  links:
    - endpoints: ["ceos1:eth1", "ceos2:eth1"]
```

and if you provide
