### ISSUE TITLE
MgmtIPv4PrefixLength, MgmtIPv6Address and MgmtIPv6PrefixLength not set when using custom startup-config

### ISSUE THREAD

**Issue by UchihaItachiSama** [srl-labs/containerlab#528]
- Node: `ceos Arista cEOS`

- Version: 1.15.2

- Feature: `startup-config`

- Issue details:

When using custom `startup-config` file for ceos the  MgmtIPv4PrefixLength, MgmtIPv6Address and MgmtIPv6PrefixLength fields are not getting set.

The custom startup-config is similar to (https://github.com/srl-labs/containerlab/blob/master/nodes/ceos/ceos.cfg)

```css
hostname {{ .ShortName }}
username admin privilege 15 secret admin
!
service routing protocols model multi-agent
!
vrf instance MGMT
!
interface Management0
   description oob_management
   vrf MGMT
{{ if .MgmtIPv4Address }}   ip address {{ .MgmtIPv4Address }}/{{ .MgmtIPv4PrefixLength }}{{end}}
{{ if .MgmtIPv6Address }}   ipv6 address {{ .MgmtIPv6Address }}/{{ .MgmtIPv6PrefixLength }}{{end}}
!
management api gnmi
   transport grpc default
      vrf MGMT
!
management api netconf
   transport ssh default
      vrf MGMT
!
management api http-commands
   protocol https
   no shutdown
   !
   vrf MGMT
      no shutdown
!
end
```

When using this in the topology definition file as follows:

```yaml
name: avdasymirb

mgmt:
  network: ceos_clab                
  ipv4_subnet: 172.100.100.0/24       
  ipv6_subnet: 2001:172:100:100::/80

topology:
  kinds:
    ceos:
      startup-config: ceos_lab_template/ceos.cfg
  nodes:
    spine1:
      kind: ceos
      image: ceosimage:4.26.1F
      mgmt_ipv4: 172.100.100.2
    spine2:
      kind: ceos
      image: ceosimage:4.26.1F
      mgmt_ipv4: 172.100.100.3
    leaf1a:
      kind: ceos
      image: ceosimage:4.26.1F
      mgmt_ipv4: 172.100.100.4
    leaf1b:
      kind: ceos
      image: ceosimage:4.26.1F
      mgmt_ipv4: 172.100.100.5
```

but the generated startup-config does not include the MgmtIPv4PrefixLength, MgmtIPv6Address and MgmtIPv6PrefixLength fields

```yaml
INFO[0000] [DEBUG] generating config for node leaf2a from file /home/babayaga/evpn-vxlan-examples/ceos_lab_template/ceos.cfg
INFO[0000] Creating container: spine1
INFO[0000] [DEBUG] node 'spine1' generated config: hostname spine1
INFO[0000] username admin privilege 15 secret admin
INFO[0000] !
INFO[0000] service routing protocols model multi-agent
INFO[0000] !
INFO[0000] vrf instance MGMT
INFO[0000] !
INFO[0000] interface Management0
INFO[0000]    description oob_management
INFO[0000]    vrf MGMT
INFO[0000]    ip address 172.100.100.2/0
INFO[0000]
INFO[0000] !
```

When not using the custom startup-config the MgmtIPv4PrefixLength, MgmtIPv6Address and MgmtIPv6PrefixLength fields are properly updated.

The issue is only limited to startup-config generation as the docker network has correct mask:
```shell
$ docker inspect clab-avdasymirb-spine1 | grep -i ip
 "IPv6Gateway": "",
                    "IPAMConfig": {
                        "IPv4Address": "172.100.100.2"
                    "IPAddress": "172.100.100.2",
                    "IPPrefixLen": 24,
                    "IPv6Gateway": "2001:172:100:100::1",
                    "GlobalIPv6Address": "2001:172:100:100::8",
                    "GlobalIPv6PrefixLen": 80,
```
