### ISSUE TITLE
Additional Ansible groups

### ISSUE THREAD

**Issue by sc68cal** [srl-labs/containerlab#537]
It would be useful to be able to have additional Ansible groups be generated in the ansible inventory file. For example if you have a spine/leaf topology it would be great to be able to split out the two layers into different ansible groups, instead of only having the `ceos` group (if you are using Arista cEOS containers) and having to constantly fiddle with `--limit`s

**Comment by hellt** [comment]
makes sense
I think this can be done  with `labels`.

For instance, the group that the node will be part of can be conveyed via `ansible-group` label. If this is set, then the node becomes a part of this group

```yaml
nodes:
  ceos1:
    labels:
      ansible-group: leaf
  ceos2:
    labels:
      ansible-group: spine
```
