### ISSUE TITLE
Missing IPv6 LLA on veth interfaces

### ISSUE THREAD

**Issue by 7oku** [srl-labs/containerlab#551]
Hi, 

I'm using the awesome cvx images from [networkop](https://github.com/networkop) and want to lab out a topology with l3 to the host using bgp unnumbered. For that we use IPv6 LLA addresses to establish the bgp session between the vms and the network devices.
However, while being fine at the mgmt interfaces, the veth interfaces between the containers do not generate IPv6 LLA addresses. I tried this with different NOS and OS images.

topo:
```
+----+--------------------+--------------+-------------------------+-------+-------+---------+-----------------+----------------------+
| #  |        Name        | Container ID |          Image          | Kind  | Group |  State  |  IPv4 Address   |     IPv6 Address     |
+----+--------------------+--------------+-------------------------+-------+-------+---------+-----------------+----------------------+
|  1 | clab-lab-provider1 | e28ee2490557 | networkop/cx:4.4.0      | cvx   |       | running | 172.20.20.4/24  | 2001:172:20:20::4/64 |
|  2 | clab-lab-provider2 | b3cc87afd7be | networkop/cx:4.4.0      | cvx   |       | running | 172.20.20.10/24 | 2001:172:20:20::a/64 |
|  3 | clab-lab-provider3 | 84ccd3b08699 | networkop/cx:4.4.0      | cvx   |       | running | 172.20.20.6/24  | 2001:172:20:20::6/64 |
|  4 | clab-lab-provider4 | 50c1f805cfe3 | networkop/cx:4.4.0      | cvx   |       | running | 172.20.20.2/24  | 2001:172:20:20::2/64 |
|  5 | clab-lab-spine1    | fc5ba0324fc3 | networkop/cx:4.4.0      | cvx   |       | running | 172.20.20.8/24  | 2001:172:20:20::8/64 |
|  6 | clab-lab-spine2    | 6f78f1ce4be4 | networkop/cx:4.4.0      | cvx   |       | running | 172.20.20.5/24  | 2001:172:20:20::5/64 |
|  7 | clab-lab-vm1       | 15b73dd3138b | networkop/host:ifreload | linux |       | running | 172.20.20.9/24  | 2001:172:20:20::9/64 |
|  8 | clab-lab-vm2       | 1e6f02c0d67c | alpine                  | linux |       | running | 172.20.20.7/24  | 2001:172:20:20::7/64 |
|  9 | clab-lab-vm3       | 29f24c33e282 | frrouting/frr:v7.5.1    | linux |       | running | 172.20.20.3/24  | 2001:172:20:20::3/64 |
| 10 | clab-lab-vm4       | 2f1357f8a0cf | networkop/host:ifreload | linux |       | running | 172.20.20.11/24 | 2001:172:20:20::b/64 |
+----+--------------------+--------------+-------------------------+-------+-------+---------+-----------------+----------------------+
```

spine1:
```
[...]
3: bridge: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 2e:91:98:15:66:a6 brd ff:ff:ff:ff:ff:ff
95: eth0@if96: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:ac:14:14:08 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.20.20.8/24 brd 172.20.20.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 2001:172:20:20::8/64 scope global nodad
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe14:1408/64 scope link
       valid_lft forever preferred_lft forever
104: swp1@if103: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9500 qdisc noqueue state UP group default
    link/ether aa:c1:ab:59:de:3e brd ff:ff:ff:ff:ff:ff link-netnsid 2
106: swp2@if105: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9500 qdisc noqueue state UP group default
    link/ether aa:c1:ab:53:b8:58 brd ff:ff:ff:ff:ff:ff link-netnsid 1
112: swp3@if111: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9500 qdisc noqueue state UP group default
    link/ether aa:c1:ab:d5:9d:1a brd ff:ff:ff:ff:ff:ff link-netnsid 3
118: swp4@if117: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9500 qdisc noqueue state UP group default
    link/ether aa:c1:ab:04:31:30 brd ff:ff:ff:ff:ff:ff link-netnsid 4
```

vm1:
```
[...]
97: eth0@if98: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:ac:14:14:09 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.20.20.9/24 brd 172.20.20.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 2001:172:20:20::9/64 scope global nodad
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe14:1409/64 scope link
       valid_lft forever preferred_lft forever
103: eth1@if104: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9500 qdisc noqueue state UP group default
    link/ether aa:c1:ab:94:18:de brd ff:ff:ff:ff:ff:ff link-netnsid 1
109: eth2@if110: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9500 qdisc noqueue state UP group default
    link/ether aa:c1:ab:ca:5f:ea brd ff:ff:ff:ff:ff:ff link-netnsid 2
```

IPv6 is enabled for docker in `/etc/docker/daemon.json`:
```
{
  "ipv6": true,
  "fixed-cidr-v6": "2001:db8:1::/64"
}
```

Is IPv6 LLA not supported on veth interfaces? 

Thanks!

**Comment by hellt** [comment]
Hi @7oku 
I think this has to do with sysctl settings, check this https://github.com/srl-labs/containerlab/issues/92

I haven't looked in my lab yet, but I assume that ipv6 sysctl is disabled for eth1+ interfaces there

**Comment by 7oku** [comment]
Hi @hellt 

yes, seems it was disabled here. I've enabled it by bind mounting a `/etc/sysctl.d/01-enable-ipv6.conf` file containing `net.ipv6.conf.all.disable_ipv6 = 0`. Works as expected now. 

But from https://github.com/srl-labs/containerlab/pull/95 this should've been applied at least to all my `linux` kinds automatically, correct?

```
name: lab

topology:
  nodes:
    spine1:
      kind: cvx
      image: networkop/cx:4.4.0
      runtime: docker
      binds:
        - 01-enable-ipv6.conf:/etc/sysctl.d/01-enable-ipv6.conf
        - authorized_keys:/root/.ssh/authorized_keys
        - ../spine1-if:/etc/network/interfaces
        - ../spine1-frr:/etc/frr/frr.conf
        - ../daemons:/etc/frr/daemons

    vm1:
      kind: linux
      image: networkop/host:ifreload
      binds:
        - authorized_keys:/root/.ssh/authorized_keys
        - ../vm1-if:/etc/network/interfaces
        - ../vm1-frr:/etc/frr/frr.conf
        - ../host-daemons:/etc/frr/daemons

    vm2:
      kind: linux
      image: alpine
      binds:
        - authorized_keys:/root/.ssh/authorized_keys
        - ../vm2-if:/etc/network/interfaces
        - ../vm2-frr:/etc/frr/frr.conf
        - ../host-daemons:/etc/frr/daemons

  links:
    - endpoints: ["spine1:swp1", "vm1:eth1"]
    - endpoints: ["spine1:swp2", "vm2:eth1"]
```

If so, that's not the case:
```
7oku@cumuluslab:~/cumulus/lab/containerlab$ docker exec -ti clab-lab-vm1 sysctl -a | grep disable_ipv6
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.eth0.disable_ipv6 = 0
net.ipv6.conf.eth1.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 0
```

**Comment by hellt** [comment]
Hey @7oku 
yes, I see that this code got lost in some refactoring
I will bring it back

**Comment by hellt** [comment]
as for the cvx nodes, @networkop  maybe you need to add the same stuff as I did here for linux nodes - https://github.com/srl-labs/containerlab/pull/558/files#diff-c571d4c0f2a39a8d37f5a783f4afb736f8319e25cea6aebd12937036085d81e5R34

**Comment by networkop** [comment]
yeah, let me check. just passing this inside the container may not help as it won't get reflected in the FC VM. 
I may have to hard-code these settings inside the image

**Comment by hellt** [comment]
but first we need to solve the problem of gh actions not allowing us to use this wildcard sysctl

```
Error response from daemon: OCI runtime create failed: sysctl \"net.ipv6.conf.all.disable_ipv6\" not allowed in host network namespace: unknown"
```

**Comment by networkop** [comment]
@7oku can you try re-pulling `4.4.0` from the dockerhub and trying again? I believe the issue should be solved.

**Comment by networkop** [comment]
> but first we need to solve the problem of gh actions not allowing us to use this wildcard sysctl
> 
> ```
> Error response from daemon: OCI runtime create failed: sysctl \"net.ipv6.conf.all.disable_ipv6\" not allowed in host network namespace: unknown"
> ```

this is strange. why does it complain about host network namespace?

**Comment by hellt** [comment]
> this is strange. why does it complain about host network namespace?

there is a test in our pipeline that starts a container in the host networking mode. hence this error

I think what I will do for now is I will only set this sysctl if we have any veth interfaces for this node (nodes in host mode ca't have them)

**Comment by hellt** [comment]
went a simpler route - disabled this sysctl for nodes with network mode = host
181bd32

**Comment by hellt** [comment]
it is fixed in `master` and will go live with `0.16.0` release

**Comment by 7oku** [comment]
hi, 

I've manually upgraded to 0.16 beta .deb in order to get the fix and redeployed my lab. 

Good news, I can confirm ipv6 lla seems to be working 👍🏼!

`kind: host` now activates ipv6 lla instantly, even without sysctl.d bind mount in topo.yml: 

```
    vm1:
      kind: linux
      image: networkop/host:ifreload
      binds:
        - authorized_keys:/root/.ssh/authorized_keys
        - ../vm1-if:/etc/network/interfaces
        - ../vm1-frr:/etc/frr/frr.conf
        - ../host-daemons:/etc/frr/daemons
```

```
$ docker exec -ti clab-lab-vm1 ip a
[..]]
70: eth2@if71: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether aa:c1:ab:5f:1e:b1 brd ff:ff:ff:ff:ff:ff link-netnsid 2
    inet6 fe80::a8c1:abff:fe5f:1eb1/64 scope link
       valid_lft forever preferred_lft forever
78: eth1@if79: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether aa:c1:ab:7d:cb:a4 brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::a8c1:abff:fe7d:cba4/64 scope link
       valid_lft forever preferred_lft forever
```

@networkop `kind: cvx` first didn't work, but after some 30ish seconds they appeared here as well. I assume that's just the delay 
 due to the slightly longer boot up time of the NOS in comparison to the small linux containers:

```
$ docker exec -ti clab-lab-spine1 ip a
[...]
102: swp4@if101: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9500 qdisc noqueue state UP group default
    link/ether aa:c1:ab:65:50:00 brd ff:ff:ff:ff:ff:ff link-netnsid 2
    inet6 fe80::a8c1:abff:fe65:5000/64 scope link
       valid_lft forever preferred_lft forever
106: swp1@if105: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9500 qdisc noqueue state UP group default
    link/ether aa:c1:ab:d7:d7:74 brd ff:ff:ff:ff:ff:ff link-netnsid 3
    inet6 fe80::a8c1:abff:fed7:d774/64 scope link
       valid_lft forever preferred_lft forever
114: swp2@if113: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9500 qdisc noqueue state UP group default
    link/ether aa:c1:ab:c3:1f:b2 brd ff:ff:ff:ff:ff:ff link-netnsid 4
    inet6 fe80::a8c1:abff:fec3:1fb2/64 scope link
       valid_lft forever preferred_lft forever
116: swp3@if115: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9500 qdisc noqueue state UP group default
    link/ether aa:c1:ab:a4:59:1a brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::a8c1:abff:fea4:591a/64 scope link
       valid_lft forever preferred_lft forever
```

All in all, everything fine! Thanks for your awesome and quick support!
