### ISSUE TITLE
No interfaces on one of routers

### ISSUE THREAD

**Issue by static33rus** [srl-labs/containerlab#561]
Hi, i am new with contrainerlab and i faced with problems. First, i tried to create lab with csr1000v, but after wasting of the whole day (because there were no interfaces except management) i decided to try another image.
I created simple lab using arista-vEOS
```
name: images
topology:
  nodes:
    vr1:
      image: vrnetlab/vr-veos:4.25.1F
      kind: vr-veos 
    vr2:
      image: vrnetlab/vr-veos:4.25.1F
      kind: vr-veos
  links:
    - endpoints: ["vr1:eth1", "vr2:eth1"]
```
As you can see, both routers vr1 and vr2 are indentical, but after loading, one router had an interface Ethernet1, but another router not
I attached logs from both containers in this issue
qemu cmd on first container:
`2021-07-30 15:01:00,608: vrnetlab   DEBUG    joined cmd: qemu-system-x86_64 -enable-kvm -display none -machine pc -monitor tcp:0.0.0.0:4000,server,nowait -m 2048 -serial telnet:0.0.0.0:5000,server,nowait -drive if=ide,file=/vEOS64-lab-4.25.1F-overlay.vmdk -cpu host,level=9 -smp 2,sockets=1,cores=1 -device pci-bridge,chassis_nr=1,id=pci.1 -device e1000,netdev=p00,mac=52:54:00:c2:45:00,bus=pci.1,addr=0x2 -netdev user,id=p00,net=10.0.0.0/24,tftp=/tftpboot,hostfwd=tcp::2022-10.0.0.15:22,hostfwd=udp::2161-10.0.0.15:161,hostfwd=tcp::2830-10.0.0.15:830,hostfwd=tcp::2080-10.0.0.15:80,hostfwd=tcp::2443-10.0.0.15:443,hostfwd=tcp::16030-10.0.0.15:6030`
and in second:
`2021-07-30 15:01:01,430: vrnetlab   DEBUG    ['qemu-system-x86_64', '-enable-kvm', '-display', 'none', '-machine', 'pc', '-monitor', 'tcp:0.0.0.0:4000,server,nowait', '-m', '2048', '-serial', 'telnet:0.0.0.0:5000,server,nowait', '-drive', 'if=ide,file=/vEOS64-lab-4.25.1F-overlay.vmdk', '-cpu', 'host,level=9', '-smp', '2,sockets=1,cores=1', '-device', 'pci-bridge,chassis_nr=1,id=pci.1', '-device', 'e1000,netdev=p00,mac=52:54:00:ff:8c:00,bus=pci.1,addr=0x2', '-netdev', 'user,id=p00,net=10.0.0.0/24,tftp=/tftpboot,hostfwd=tcp::2022-10.0.0.15:22,hostfwd=udp::2161-10.0.0.15:161,hostfwd=tcp::2830-10.0.0.15:830,hostfwd=tcp::2080-10.0.0.15:80,hostfwd=tcp::2443-10.0.0.15:443,hostfwd=tcp::16030-10.0.0.15:6030', '-device', 'e1000,netdev=p01,mac=52:54:00:f0:05:01,bus=pci.1,addr=0x3', '-netdev', 'tap,id=p01,ifname=tap1,script=/etc/tc-tap-ifup,downscript=no']
2021-07-30 15:01:01,430: vrnetlab   DEBUG    joined cmd: qemu-system-x86_64 -enable-kvm -display none -machine pc -monitor tcp:0.0.0.0:4000,server,nowait -m 2048 -serial telnet:0.0.0.0:5000,server,nowait -drive if=ide,file=/vEOS64-lab-4.25.1F-overlay.vmdk -cpu host,level=9 -smp 2,sockets=1,cores=1 -device pci-bridge,chassis_nr=1,id=pci.1 -device e1000,netdev=p00,mac=52:54:00:ff:8c:00,bus=pci.1,addr=0x2 -netdev user,id=p00,net=10.0.0.0/24,tftp=/tftpboot,hostfwd=tcp::2022-10.0.0.15:22,hostfwd=udp::2161-10.0.0.15:161,hostfwd=tcp::2830-10.0.0.15:830,hostfwd=tcp::2080-10.0.0.15:80,hostfwd=tcp::2443-10.0.0.15:443,hostfwd=tcp::16030-10.0.0.15:6030 -device e1000,netdev=p01,mac=52:54:00:f0:05:01,bus=pci.1,addr=0x3 -netdev tap,id=p01,ifname=tap1,script=/etc/tc-tap-ifup,downscript=no`

as you can see, script launch.py generated different cmds
containerlab version version: 0.15.5

[vr1log.txt](https://github.com/srl-labs/containerlab/files/6908486/vr1log.txt)
[vr2log.txt](https://github.com/srl-labs/containerlab/files/6908487/vr2log.txt)

**Comment by hellt** [comment]
Hi!
Thanks for reporting that. There is a PR in vrnetlab that seems to catch
all that missing interfaces. I'll check over the weekend and get back to you

**Comment by static33rus** [comment]
After some tries i was able to run this lab adding delay for one node
```
name: images
topology:
  nodes:
    vr1:
      image: vrnetlab/vr-veos:4.25.1F
      kind: vr-veos
      env:
        # boot delay in seconds
        BOOT_DELAY: 30 
    vr2:
      image: vrnetlab/vr-veos:4.25.1F
      kind: vr-veos
  links:
    - endpoints: ["vr2:eth1", "vr1:eth1"]
```
Now, all routers have data interfaces. Is it a normal behaviour or a bug? I thought i have to use delay if i run a lot of labs
And i still have an issue with csr1000v
