### ISSUE TITLE
containerlab connects the management IP incorrectly

### ISSUE THREAD

**Issue by sc68cal** [srl-labs/containerlab#569]
I recently upgraded my lab and am seeing an issue where some containers are getting wired incorrectly. It appears that `clab-tes-lab-spine2` is getting attached to `172.20.20.3` and `172.20.20.4`

```
 » cat containerlab
all:
  children:
    ceos:
      hosts:
        clab-tes-lab-oob-agg1:
          ansible_host: 172.20.20.5
        clab-tes-lab-oob-agg2:
          ansible_host: 172.20.20.6
        clab-tes-lab-spine1:
          ansible_host: 172.20.20.2
        clab-tes-lab-spine2:
          ansible_host: 172.20.20.3
        clab-tes-lab-spine3:
          ansible_host: 172.20.20.9
        clab-tes-lab-spine4:
          ansible_host: 172.20.20.4
        clab-tes-lab-tes-spine1:
          ansible_host: 172.20.20.7
        clab-tes-lab-tes-spine2:
          ansible_host: 172.20.20.8
    oob_agg:
      hosts:
        clab-tes-lab-oob-agg1:
          ansible_host: 172.20.20.5
        clab-tes-lab-oob-agg2:
          ansible_host: 172.20.20.6
    spines:
      hosts:
        clab-tes-lab-spine1:
          ansible_host: 172.20.20.2
        clab-tes-lab-spine2:
          ansible_host: 172.20.20.3
        clab-tes-lab-spine3:
          ansible_host: 172.20.20.9
        clab-tes-lab-spine4:
          ansible_host: 172.20.20.4
    upstream_spines:
      hosts:
        clab-tes-lab-tes-spine1:
          ansible_host: 172.20.20.7
        clab-tes-lab-tes-spine2:
          ansible_host: 172.20.20.8

» ssh admin@172.20.20.4
Warning: Permanently added '172.20.20.4' (ECDSA) to the list of known hosts.
spine2>show version
 cEOSLab
Hardware version:
Serial number:
Hardware MAC address: 001c.7397.5b78
System MAC address: 001c.7397.5b78

Software image version: 4.26.1F-22602519.4261F (engineering build)
Architecture: x86_64
Internal build version: 4.26.1F-22602519.4261F
Internal build ID: 1eca5f74-3ced-441a-9137-c966e8f0319d
Image format version: 01.00

cEOS tools version: 1.1
Kernel version: 4.15.0-151-generic

Uptime: 0 weeks, 0 days, 0 hours and 25 minutes
Total memory: 8068908 kB
Free memory: 651652 kB


» ssh admin@172.20.20.3
spine2#show version
 cEOSLab
Hardware version:
Serial number:
Hardware MAC address: 001c.7397.5b78
System MAC address: 001c.7397.5b78

Software image version: 4.26.1F-22602519.4261F (engineering build)
Architecture: x86_64
Internal build version: 4.26.1F-22602519.4261F
Internal build ID: 1eca5f74-3ced-441a-9137-c966e8f0319d
Image format version: 01.00

cEOS tools version: 1.1
Kernel version: 4.15.0-151-generic

Uptime: 0 weeks, 0 days, 0 hours and 25 minutes
Total memory: 8068908 kB
Free memory: 649868 kB

spine2#exit
Connection to 172.20.20.3 closed.


scollins@griffin:~$ docker ps
CONTAINER ID   IMAGE          COMMAND                  CREATED          STATUS          PORTS     NAMES
7ed82c97bec8   ceos:4.26.1F   "/sbin/init systemd.…"   28 minutes ago   Up 28 minutes             clab-tes-lab-spine3
8931ba70e280   ceos:4.26.1F   "/sbin/init systemd.…"   28 minutes ago   Up 28 minutes             clab-tes-lab-spine1
e0912a074fe8   ceos:4.26.1F   "/sbin/init systemd.…"   28 minutes ago   Up 28 minutes             clab-tes-lab-spine2
68ab24f43394   ceos:4.26.1F   "/sbin/init systemd.…"   28 minutes ago   Up 28 minutes             clab-tes-lab-tes-spine1
cb5c8317ad36   ceos:4.26.1F   "/sbin/init systemd.…"   28 minutes ago   Up 28 minutes             clab-tes-lab-oob-agg2
e06c88e1ecb0   ceos:4.26.1F   "/sbin/init systemd.…"   28 minutes ago   Up 28 minutes             clab-tes-lab-tes-spine2
fc68aaea4da4   ceos:4.26.1F   "/sbin/init systemd.…"   28 minutes ago   Up 28 minutes             clab-tes-lab-oob-agg1
3ac6adeca493   ceos:4.26.1F   "/sbin/init systemd.…"   28 minutes ago   Up 28 minutes             clab-tes-lab-spine4


scollins@griffin:~$ docker exec -it 3ac6adeca493 Cli
spine4>show version
 cEOSLab
Hardware version:
Serial number:
Hardware MAC address: 001c.73ea.ff02
System MAC address: 001c.73ea.ff02

Software image version: 4.26.1F-22602519.4261F (engineering build)
Architecture: x86_64
Internal build version: 4.26.1F-22602519.4261F
Internal build ID: 1eca5f74-3ced-441a-9137-c966e8f0319d
Image format version: 01.00

cEOS tools version: 1.1
Kernel version: 4.15.0-151-generic

Uptime: 0 weeks, 0 days, 0 hours and 27 minutes
Total memory: 8068908 kB
Free memory: 637548 kB

scollins@griffin:~$ containerlab version

                           _                   _       _
                 _        (_)                 | |     | |
 ____ ___  ____ | |_  ____ _ ____   ____  ____| | ____| | _
/ ___) _ \|  _ \|  _)/ _  | |  _ \ / _  )/ ___) |/ _  | || \
( (__| |_|| | | | |_( ( | | | | | ( (/ /| |   | ( ( | | |_) )
\____)___/|_| |_|\___)_||_|_|_| |_|\____)_|   |_|\_||_|____/

    version: 0.16.0
     commit: 4d15005
       date: 2021-08-03T09:03:15Z
     source: https://github.com/srl-labs/containerlab
 rel. notes: https://containerlab.srlinux.dev/rn/0.16/
```

**Comment by hellt** [comment]
Hi
Check /etc/hosts and remove potential duplicate entries which are not
enclosed in CLAB-labname-START/END markers

**Comment by sc68cal** [comment]
```
127.0.0.1 localhost
127.0.1.1 griffin
# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.100.100.204	clab-tes-lab-spine4
2001:172:101:100::7	clab-tes-lab-spine4
172.100.100.251	clab-tes-lab-tes-spine1
2001:172:101:100::4	clab-tes-lab-tes-spine1
172.100.100.202	clab-tes-lab-spine2
2001:172:101:100::5	clab-tes-lab-spine2
172.100.100.201	clab-tes-lab-spine1
2001:172:101:100::6	clab-tes-lab-spine1
172.100.100.203	clab-tes-lab-spine3
2001:172:101:100::3	clab-tes-lab-spine3
172.100.100.252	clab-tes-lab-tes-spine2
2001:172:101:100::2	clab-tes-lab-tes-spine2
172.20.20.7	clab-tes-lab-spine1
2001:172:20:20::7	clab-tes-lab-spine1

172.20.20.9	clab-tes-lab-spine4
2001:172:20:20::9	clab-tes-lab-spine4
172.20.20.8	clab-tes-lab-spine3
2001:172:20:20::8	clab-tes-lab-spine3
172.20.20.2	clab-tes-lab-spine1
2001:172:20:20::2	clab-tes-lab-spine1
172.20.20.3	clab-tes-lab-tes-spine2
2001:172:20:20::3	clab-tes-lab-tes-spine2
172.20.20.5	clab-tes-lab-spine2
2001:172:20:20::5	clab-tes-lab-spine2
172.20.20.6	clab-tes-lab-oob-agg1
2001:172:20:20::6	clab-tes-lab-oob-agg1
172.20.20.7	clab-tes-lab-oob-agg2
2001:172:20:20::7	clab-tes-lab-oob-agg2
172.20.20.4	clab-tes-lab-tes-spine1
2001:172:20:20::4	clab-tes-lab-tes-spine1
###### CLAB-tes-lab-START ######
172.20.20.3	clab-tes-lab-spine3
172.20.20.6	clab-tes-lab-spine1
172.20.20.4	clab-tes-lab-spine2
172.20.20.7	clab-tes-lab-tes-spine1
172.20.20.8	clab-tes-lab-oob-agg2
172.20.20.9	clab-tes-lab-tes-spine2
172.20.20.5	clab-tes-lab-oob-agg1
172.20.20.2	clab-tes-lab-spine4
2001:172:20:20::3	clab-tes-lab-spine3
2001:172:20:20::6	clab-tes-lab-spine1
2001:172:20:20::4	clab-tes-lab-spine2
2001:172:20:20::7	clab-tes-lab-tes-spine1
2001:172:20:20::8	clab-tes-lab-oob-agg2
2001:172:20:20::9	clab-tes-lab-tes-spine2
2001:172:20:20::5	clab-tes-lab-oob-agg1
2001:172:20:20::2	clab-tes-lab-spine4
###### CLAB-tes-lab-END ######
```

**Comment by sc68cal** [comment]
So, I think we need to have containerlab clean itself up better, if it is putting things in `/etc/hosts`

**Comment by sc68cal** [comment]
OK, next time I promise to RTFM :)

**Comment by sc68cal** [comment]
I think we still have an issue, even after clearing out the `/etc/hosts` file:
```
ssh admin@clab-tes-lab-tes-spine1
The authenticity of host 'clab-tes-lab-tes-spine1 (2001:172:20:20::4)' can't be established.
ECDSA key fingerprint is SHA256:G48iqwIpNaiUiicRId06H1Ct94VFdubWDW1y2jOdikg.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'clab-tes-lab-tes-spine1,2001:172:20:20::4' (ECDSA) to the list of known hosts.
Password:
spine4>
```

**Comment by sc68cal** [comment]
```
###### CLAB-tes-lab-START ######
172.20.20.2	clab-tes-lab-spine1
172.20.20.3	clab-tes-lab-spine3
172.20.20.9	clab-tes-lab-spine2
172.20.20.7	clab-tes-lab-oob-agg1
172.20.20.4	clab-tes-lab-tes-spine1
172.20.20.6	clab-tes-lab-oob-agg2
172.20.20.8	clab-tes-lab-spine4
172.20.20.5	clab-tes-lab-tes-spine2
2001:172:20:20::2	clab-tes-lab-spine1
2001:172:20:20::3	clab-tes-lab-spine3
2001:172:20:20::9	clab-tes-lab-spine2
2001:172:20:20::7	clab-tes-lab-oob-agg1
2001:172:20:20::4	clab-tes-lab-tes-spine1
2001:172:20:20::6	clab-tes-lab-oob-agg2
2001:172:20:20::8	clab-tes-lab-spine4
2001:172:20:20::5	clab-tes-lab-tes-spine2
###### CLAB-tes-lab-END ######
```

```yaml
all:
  children:
    ceos:
      hosts:
        clab-tes-lab-oob-agg1:
          ansible_host: 172.20.20.8
        clab-tes-lab-oob-agg2:
          ansible_host: 172.20.20.6
        clab-tes-lab-spine1:
          ansible_host: 172.20.20.2
        clab-tes-lab-spine2:
          ansible_host: 172.20.20.3
        clab-tes-lab-spine3:
          ansible_host: 172.20.20.5
        clab-tes-lab-spine4:
          ansible_host: 172.20.20.7
        clab-tes-lab-tes-spine1:
          ansible_host: 172.20.20.4
        clab-tes-lab-tes-spine2:
          ansible_host: 172.20.20.9
    oob_agg:
      hosts:
        clab-tes-lab-oob-agg1:
          ansible_host: 172.20.20.8
        clab-tes-lab-oob-agg2:
          ansible_host: 172.20.20.6
    spines:
      hosts:
        clab-tes-lab-spine1:
          ansible_host: 172.20.20.2
        clab-tes-lab-spine2:
          ansible_host: 172.20.20.3
        clab-tes-lab-spine3:
          ansible_host: 172.20.20.5
        clab-tes-lab-spine4:
          ansible_host: 172.20.20.7
    upstream_spines:
      hosts:
        clab-tes-lab-tes-spine1:
          ansible_host: 172.20.20.4
        clab-tes-lab-tes-spine2:
          ansible_host: 172.20.20.9
```
