### ISSUE TITLE
Add ability to name nodes instead of using automatically generated names

### ISSUE THREAD

**Issue by sc68cal** [srl-labs/containerlab#619]
For a while, I have been using containerlab for local development, for a set of routers that I have in production, that are orchestrated via Ansible.

I use the automatically generated containerlab Ansible inventory file, and then I have created `symlinks` in the `host_var` directory between the containerlab host, and the router it is simulating in local development.

Here is the generated Ansible inventory file that containerlab creates.

```yaml
  children:
    ceos:
      hosts:
        clab-tes-lab-oob-agg1:
          ansible_host: 172.20.20.8
        clab-tes-lab-oob-agg2:
          ansible_host: 172.20.20.9
        clab-tes-lab-spine1:
          ansible_host: 172.20.20.2
        clab-tes-lab-spine2:
          ansible_host: 172.20.20.3
        clab-tes-lab-spine3:
          ansible_host: 172.20.20.4
        clab-tes-lab-spine4:
          ansible_host: 172.20.20.5
        clab-tes-lab-tes-spine1:
          ansible_host: 172.20.20.6
        clab-tes-lab-tes-spine2:
          ansible_host: 172.20.20.7
    oob_agg:
      hosts:
        clab-tes-lab-oob-agg1:
          ansible_host: 172.20.20.8
        clab-tes-lab-oob-agg2:
          ansible_host: 172.20.20.9
    spines:
      hosts:
        clab-tes-lab-spine1:
          ansible_host: 172.20.20.2
        clab-tes-lab-spine2:
          ansible_host: 172.20.20.3
        clab-tes-lab-spine3:
          ansible_host: 172.20.20.4
        clab-tes-lab-spine4:
          ansible_host: 172.20.20.5
    upstream_spines:
      hosts:
        clab-tes-lab-tes-spine1:
          ansible_host: 172.20.20.6
        clab-tes-lab-tes-spine2:
          ansible_host: 172.20.20.7
```

I have the following layout in my `host_var` directory for the Ansible code that orchestrates these switches:

```
$ ls -l host_vars
clab-tes-lab-oob-agg1 -> oob-agg1.example.com
clab-tes-lab-oob-agg2 -> oob-agg2.example.com
clab-tes-lab-spine1 -> spine1.example.com
clab-tes-lab-spine2 -> spine2.example.com
clab-tes-lab-spine3 -> spine3.example.com
clab-tes-lab-spine4 -> spine4.example.com
clab-tes-lab-tes-spine1
clab-tes-lab-tes-spine2
oob-agg1.example.com
oob-agg2.example.com
spine1.example.com
spine2.example.com
spine3.example.com
spine4.example.com
```
This has worked quite well so far, because it just has Ansible load up the host_var file for spine1.example.com when I run it `ansible-playbook -i containerlab` 

The problem is that my Ansible automation is getting a bit more complex, and is using NetBox API calls to get information to configure interfaces. I am relying on `inventory_hostname` to be set, which means that the trick I am doing of `symlink`ing won't work for this case, without making things more complicated.

It would be nice to just be able to override containerlab's node name generation based on the topology file and substitute in my own, so it maps back to Ansible more cleanly.

**Comment by sc68cal** [comment]
Let me see if fiddling with `prefix` is what I need - https://containerlab.srlinux.dev/manual/topo-def-file/#prefix

**Comment by sc68cal** [comment]
Prefix helps, but it would be nice if I could set something like `suffix`, or have the `name` parameter be used as a suffix instead of a prefix....

**Comment by sc68cal** [comment]
I see that nodes have an `FQDN` attribute, perhaps that?

**Comment by hellt** [comment]
@sc68cal what if you use `prefix: ""` and name your nodes as

```
nodes:
    spine1.example.com:
      kind: ceos
```
?

**Comment by sc68cal** [comment]
yup that works! thanks

**Comment by hellt** [comment]
Than maybe the PR with trailing domain is not needed?

**Comment by sc68cal** [comment]
So, I am actually having issues with this still. I will provide information shortly, but I am still seeing the `name` attribute of the topology file being added as a prefix to nodes, when the ansible inventory is being generated.

**Comment by sc68cal** [comment]
```yaml
name: tes-lab-spines
prefix: ""

# Define our own network for management
# so we can statically assign management IP's
#
# This works around https://github.com/srl-labs/containerlab/issues/569
mgmt:
  network: ceos_clab
  ipv4_subnet: 172.20.20.0/24
  ipv6_subnet: 2001:172:20:20::/80

topology:
  kinds:
    ceos:
      kind: ceos
      image: ceos:4.26.1F
  nodes:
    spine1.example.com:

```

```yaml
     spines:
      hosts:
        tes-lab-spines-spine1.example.com:
          ansible_host: 172.20.20.2
        tes-lab-spines-spine2.example.com:
          ansible_host: 172.20.20.3
        tes-lab-spines-spine3.example.com:
          ansible_host: 172.20.20.4
        tes-lab-spines-spine4.example.com:
          ansible_host: 172.20.20.5
```
