### ISSUE TITLE
Missing state for ignite linux nodes

### ISSUE THREAD

**Issue by robertvolkmann** [srl-labs/containerlab#909]
I'm struggling with the ignite runtime. Deploying the topology
```
name: clab
prefix: ""

mgmt:
  network: bridge

topology:
  kinds:
    linux:
      image: weaveworks/ignite-ubuntu:20.04
      kernel: weaveworks/ignite-kernel:5.10.51
      runtime: ignite
      sandbox: weaveworks/ignite:v0.10.0
  nodes:
    host1:
      kind: linux
    host2:
      kind: linux
  links:
    - endpoints: ["host1:eth1", "host2:eth1"]
```
results into
```
+---+-------+--------------+------------------------------------------+-------+-------+---------------+--------------+
| # | Name  | Container ID |                  Image                   | Kind  | State | IPv4 Address  | IPv6 Address |
+---+-------+--------------+------------------------------------------+-------+-------+---------------+--------------+
| 1 | host1 | 068eb650696f | docker.io/weaveworks/ignite-ubuntu:20.04 | linux |       | 172.17.0.3/24 | N/A          |
| 2 | host2 | 5e78e5702106 | docker.io/weaveworks/ignite-ubuntu:20.04 | linux |       | 172.17.0.2/24 | N/A          |
+---+-------+--------------+------------------------------------------+-------+-------+---------------+--------------+
```
I don't see the state of the containers. The interface `eth1` is down in both ignite containers.
```
$ docker attach ignite-378c53bc930e70bf
# ip link show eth1
5: eth1: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast state DOWN mode DEFAULT group default qlen 1000
    link/ether aa:c1:ab:e8:80:dc brd ff:ff:ff:ff:ff:ff
```
Any idea?
