### ISSUE TITLE
inspect doesn't output IP address when kindnet `kind` network is used

### ISSUE THREAD

**Issue by hellt** [srl-labs/containerlab#932]
to reproduce

1. create a kind cluster
2. docker network named `kind` will be created
3. create a topology that uses this `kind` network as the management net
```yaml
name: custnet
mgmt:
  network: kind
  ipv4_subnet: 172.18.0.0/16
topology:
  nodes:
    srl:
      kind: srl
      mgmt_ipv4: 172.18.0.100
      image: ghcr.io/nokia/srlinux
```

run the topology. It outputs IP addresses as was assigned by the user. But `containerlab inspect --all` will not list those IP addresses
