### ISSUE TITLE
Sharing network namespace with containers created out of containerlab

### ISSUE THREAD

**Issue by YutaroHayakawa** [srl-labs/containerlab#964]
We Cilium team love containerlab and used it to demonstrate our BGP feature (https://twitter.com/go_containerlab/status/1554050860254126082 CC:@nvibert). It makes [Kind](https://kind.sigs.k8s.io/) k8s nodes part of the containerlab topology and runs Cilium on top of that. Actually, it doesn't work out of the box, and we needed to do some hacky stuff. I'm filing this issue to explain the problem we met and suggest a possible solution and make a discussion.

Below is how we make the kind node part of the containerlab.

**containerlab topology file**
```
name: kind-integration
topology:
  kinds:
    linux:
      cmd: bash
  nodes:
    router0:
      kind: linux
      image: nicolaka/netshoot:latest
      exec:
      - ip addr add 10.0.0.1/24 dev net0
      - ip addr add 10.0.1.1/24 dev net1
    server0:
      kind: linux
      image: nicolaka/netshoot:latest
      network-mode: container:control-plane
      exec:
      - ip addr add 10.0.0.2/24 dev net0
      - ip route add 10.0.1.0/24 via 10.0.0.1
    server1:
      kind: linux
      image: nicolaka/netshoot:latest
      network-mode: container:worker
      exec:
      - ip addr add 10.0.1.2/24 dev net0
      - ip route add 10.0.0.0/24 via 10.0.1.1
  links:
  - endpoints: ["router0:net0", "server0:net0"]
  - endpoints: ["router0:net1", "server1:net0"]
```

**kind manifest**
```
kind: Cluster
name: clab-kind-integration
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
```

**How to deploy**
```
kind create cluster --config cluster.yaml
sudo containerlab -t topo.yaml deploy
```

What we do is basically create the kind nodes and containerlab nodes sharing the network namespace. So that we can advertise PodCIDR to the containerlab network through BGP from Cilium agent running on kind node and make containers reachable from containerlab network side.

However, the current `network-mode: container:<foo>` only accepts the node name within the same topology file on the `<foo>` part. So, the hack we do is abusing the naming scheme of the containerlab and kind.

When we name the kind cluster `clab-kind-integration`, it creates docker container named `clab-kind-integration-control-plane` and `clab-kind-integration-worker`. This aligns with the naming scheme of Linux containers when we name the containerlab topology `kind-integration`.

Then containerlab resolves container name of `<foo>` part of `network-mode: container:<foo>` as `clab-<topology name>-<foo>`. In this example topology, we specify `container:control-plane` and `container:worker`, so it they are resolved as `container:clab-kind-integration-control-plane` and `container:clab-kind-integration-worker` which is the same name as kind nodes. Since containerlab passes it to Docker without checking if the containers are part of the lab, we can share the network namespace of containerlab nodes and external containers in this way.

However, this is an API abuse, and we have a limitation of the naming scheme. So, I'll file the issue here to suggest officially supporting sharing network namespace with external containers. One idea to achieve that is to add a new network mode like `external-container: <foo>`. Extending the existing `container` network mode is also an option, but I couldn't come up with a good way to resolve the case that the names of "internal" and "external" containers are conflicting (e.g. there is a node name `foo` in the topology and we have container `foo` externally as well).

Any comments are appreciated. Thanks in advance!
